Repository kubernetes-sigs/controller-runtime, pull requests merged in 2018-06, with the labels that each got.

#1 Setup controller-platform repo from the template
  .gitignore
  CONTRIBUTING.md
  LICENSE
  OWNERS
  OWNERS_ALIASES
  README.md
  RELEASE.md
  SECURITY_CONTACTS
  code-of-conduct.md
Labels: cncf-cla: yes, size/M

#3 Update test.sh to run go vet and go fmt
  example/main.go
  pkg/controller/eventhandler/eventhandler_test.go
  pkg/controller/reconcile/example_test.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#4 Add golint to travis
  .travis.yml
  example/main.go
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_manager.go
  pkg/controller/controller_suite_test.go
  pkg/controller/doc.go
  pkg/controller/eventhandler/enqueue.go
  pkg/controller/eventhandler/enqueue_mapped.go
  pkg/controller/eventhandler/enqueue_owner.go
  pkg/controller/eventhandler/eventhandler.go
  pkg/controller/eventhandler/eventhandler_test.go
  pkg/controller/eventhandler/example_test.go
  pkg/controller/example_test.go
  pkg/controller/predicate/example_test.go
  pkg/controller/predicate/predicate.go
  pkg/controller/predicate/predicate_test.go
  pkg/controller/reconcile/example_test.go
  pkg/controller/reconcile/reconcile.go
  pkg/controller/reconcile/reconcile_test.go
  pkg/controller/source/internal/internal_test.go
  pkg/controller/source/source.go
  pkg/controller/source/source_integration_test.go
  pkg/controller/source/source_suite_test.go
  pkg/controller/source/source_test.go
  pkg/runtime/inject/inject.go
  pkg/test/server.go
  test.sh
Labels: cncf-cla: yes, size/L

#7 Add metalinter to travis
  .travis.yml
Labels: cncf-cla: yes, lgtm, size/XS

#9 Get controller.go test coverage to 100%
  pkg/controller/controller.go
  pkg/controller/controller_suite_integration_test.go
  pkg/controller/controller_test.go
  pkg/controller/event/event_suite_test.go
  pkg/controller/eventhandler/eventhandler_suite_test.go
  pkg/controller/manager.go
  pkg/controller/manager_test.go
  pkg/controller/predicate/predicate_suite_test.go
  pkg/controller/reconcile/reconcile_suite_test.go
  pkg/controller/reconcile/reconciletest/reconcile.go
  pkg/controller/source/source.go
  pkg/controller/source/source_suite_test.go
Labels: cncf-cla: yes, size/XL

#11 move certprovisioner pkg
  pkg/admission/certprovisioner/certprovisioner.go
  pkg/admission/certprovisioner/certprovisioner_test.go
  pkg/admission/certprovisioner/doc.go
  pkg/admission/certprovisioner/selfsignedcertprovisioner.go
  pkg/admission/certprovisioner/selfsignedcertprovisioner_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#13 Actually run metalinter and fix lint errors
  .travis.yml
  pkg/admission/certprovisioner/selfsignedcertprovisioner_test.go
  pkg/client/cache.go
  pkg/client/cache_test.go
  pkg/controller/controller.go
  pkg/controller/controller_suite_integration_test.go
  pkg/controller/eventhandler/enqueue_owner.go
  pkg/controller/manager.go
  pkg/controller/source/source.go
  pkg/internal/admission/decode.go
  pkg/internal/admission/example_decode_test.go
  pkg/internal/admission/handler.go
  pkg/internal/admission/http.go
  pkg/internal/admission/tls.go
  pkg/internal/informer/informertest/fake_cache.go
  pkg/test/server.go
  test.sh
Labels: cncf-cla: yes, size/L

#14 Refactor informer and client packages into cache and client packages
  example/main.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer.go
  pkg/cache/informertest/fake_cache.go
  pkg/client/apiutil/apimachinery.go
  pkg/client/client.go
  pkg/client/interfaces.go
  pkg/client/split.go
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_suite_integration_test.go
  pkg/controller/controller_test.go
  pkg/controller/example_test.go
  pkg/controller/manager.go
  pkg/controller/manager_test.go
  pkg/controller/source/source.go
  pkg/controller/source/source_integration_test.go
  pkg/controller/source/source_suite_test.go
  pkg/controller/source/source_test.go
  pkg/internal/informer/cache.go
  pkg/runtime/inject/inject.go
Labels: cncf-cla: yes, size/XXL

#18 Add code coverage
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/L

#19 Enforce code coverage in travis
  pkg/event/event_suite_test.go
  pkg/event/event_test.go
  pkg/manager/manager_test.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#20 Clean up travis coverage skip list
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6 Implement the ChannelSource
  pkg/manager/internal.go
  pkg/runtime/inject/inject.go
  pkg/source/example_test.go
  pkg/source/source.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#28 Get source related tests to 100% coverage
  pkg/manager/manager_test.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 Add back coverage requirements for manager and source packages
  .travis.yml
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 Client tests
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer.go
  pkg/client/client.go
  pkg/client/client_cache.go
  pkg/client/client_suite_test.go
  pkg/client/client_test.go
  pkg/client/config/config.go
  pkg/client/interfaces.go
  pkg/client/split.go
  pkg/manager/manager.go
  pkg/reconcile/reconcile.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#29 Refactor cache package.
  pkg/cache/cache.go
  pkg/cache/cache_suite_test.go
  pkg/cache/cache_test.go
  pkg/cache/informer.go
  pkg/cache/informers.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/factory.go
  pkg/cache/internal/typed_reader.go
  pkg/cache/reader.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#35 Fixup pkg/cache with comments from #29
  pkg/cache/cache.go
  pkg/cache/informer_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/internal/informers_map.go
  pkg/cache/reader.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#38 move to sigs.k8s.io vanity url
  .travis.yml
  README.md
  example/main.go
  pkg/cache/cache.go
  pkg/cache/cache_suite_test.go
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/internal/informers_map.go
  pkg/client/client.go
  pkg/client/client_cache.go
  pkg/client/client_suite_test.go
  pkg/client/client_test.go
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/controller_test.go
  pkg/controller/example_test.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_suite_test.go
  pkg/handler/eventhandler_test.go
  pkg/handler/example_test.go
  pkg/internal/admission/example_admissionfunc_test.go
  pkg/internal/admission/example_decode_test.go
  pkg/internal/admission/example_handlefunc_test.go
  pkg/internal/admission/example_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_suite_test.go
  pkg/internal/controller/controller_test.go
  pkg/manager/example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
  pkg/predicate/example_test.go
  pkg/predicate/predicate.go
  pkg/predicate/predicate_suite_test.go
  pkg/predicate/predicate_test.go
  pkg/reconcile/example_test.go
  pkg/reconcile/reconcile_suite_test.go
  pkg/reconcile/reconcile_test.go
  pkg/reconcile/reconciletest/reconcile.go
  pkg/runtime/inject/inject.go
  pkg/source/example_test.go
  pkg/source/internal/eventsource.go
  pkg/source/internal/internal_suite_test.go
  pkg/source/internal/internal_test.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
  pkg/source/source_suite_test.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#37 Ensure that informers have the namespace index
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#23 Implement InjectRecorder
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/recorder/recorder.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/internal/recorder/recorder_suite_test.go
  pkg/internal/recorder/recorder_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/recorder/recorder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#44 Run `dep ensure` to get client-go/tools/record
  Gopkg.lock
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/BUILD
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/BUILD
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/types.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/BUILD
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/tools/record/doc.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/tools/record/events_cache.go
  vendor/k8s.io/client-go/tools/record/fake.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#47 delete Controller code for review baseline
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/controller_test.go
  pkg/controller/controllertest/doc.go
  pkg/controller/controllertest/testing.go
  pkg/controller/controllertest/util.go
  pkg/controller/doc.go
  pkg/controller/example_test.go
  pkg/doc.go
  pkg/event/event.go
  pkg/handler/doc.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_suite_test.go
  pkg/handler/eventhandler_test.go
  pkg/handler/example_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_suite_test.go
  pkg/internal/controller/controller_test.go
  pkg/manager/doc.go
  pkg/manager/example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
  pkg/manager/testutil.go
  pkg/predicate/doc.go
  pkg/predicate/example_test.go
  pkg/predicate/predicate.go
  pkg/predicate/predicate_suite_test.go
  pkg/predicate/predicate_test.go
  pkg/reconcile/doc.go
  pkg/reconcile/example_test.go
  pkg/reconcile/reconcile.go
  pkg/reconcile/reconcile_suite_test.go
  pkg/reconcile/reconcile_test.go
  pkg/reconcile/reconciletest/reconcile.go
  pkg/recorder/recorder.go
  pkg/source/doc.go
  pkg/source/example_test.go
  pkg/source/internal/eventsource.go
  pkg/source/internal/internal_suite_test.go
  pkg/source/internal/internal_test.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
  pkg/source/source_suite_test.go
  pkg/source/source_test.go
Labels: cncf-cla: yes, size/XXL

#39 Make sure cache Reader still works
  .gitignore
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#46 update test.sh to enforce coverage on inject and signals
  pkg/runtime/log/log.go
  pkg/runtime/log/log_test.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#49 Fix non-cache client list
  pkg/client/client.go
  pkg/client/client_cache.go
  pkg/client/client_test.go
  pkg/client/interfaces.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#54 Add helper function for adding OwnerReferences to metav1.Objects
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_suite_test.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/controller/controllerutil/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#22 cert provisioner
  pkg/admission/cert/generator/certgenerator.go
  pkg/admission/cert/generator/certgenerator_test.go
  pkg/admission/cert/generator/doc.go
  pkg/admission/cert/generator/fake/certgenerator.go
  pkg/admission/cert/generator/selfsigned.go
  pkg/admission/cert/generator/selfsigned_test.go
  pkg/admission/cert/writer/certwriter.go
  pkg/admission/cert/writer/certwriter_test.go
  pkg/admission/cert/writer/doc.go
  pkg/admission/cert/writer/fs.go
  pkg/admission/cert/writer/multiple.go
  pkg/admission/cert/writer/multiple_test.go
  pkg/admission/cert/writer/secret.go
  pkg/admission/cert/writer/secret_test.go
  pkg/admission/cert/writer/suite_test.go
  pkg/admission/controller.go
  pkg/admission/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#55 Fixed field selector test
  pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 address the remaining comments from #22
  pkg/admission/cert/generator/certgenerator.go
  pkg/admission/cert/writer/doc.go
  pkg/admission/cert/writer/multiple_test.go
  pkg/admission/cert/writer/secret.go
  pkg/admission/cert/writer/secret_test.go
  pkg/admission/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#60 Fix typo: kubeuilder -> kubebuilder
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#61 Address Controller lib PR comments
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#62 Scheme helper fn
  pkg/runtime/scheme/scheme.go
  pkg/runtime/scheme/scheme_suite_test.go
  pkg/runtime/scheme/scheme_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#57 Implement fs writer
  pkg/admission/cert/writer/certwriter.go
  pkg/admission/cert/writer/certwriter_test.go
  pkg/admission/cert/writer/error.go
  pkg/admission/cert/writer/fs.go
  pkg/admission/cert/writer/fs_test.go
  pkg/admission/cert/writer/internal/atomic/atomic_writer.go
  pkg/admission/cert/writer/internal/atomic/atomic_writer_test.go
  pkg/admission/cert/writer/secret.go
  pkg/admission/cert/writer/secret_test.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#64 use Add instead of AddRateLimited in eventhandlers
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#63 address feedback on PR 48
  pkg/cache/internal/informers_map.go
  pkg/controller/controller.go
  pkg/doc.go
  pkg/handler/enqueue_owner.go
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#26 Add simple application pattern package
  pkg/patterns/application/application.go
  pkg/patterns/application/application_suite_test.go
  pkg/patterns/application/application_test.go
  pkg/patterns/application/doc.go
  pkg/patterns/application/example_test.go
  pkg/patterns/operator/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#59 First pass at informer cache tests
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#53 Implement predicate
  pkg/predicate/predicate.go
  pkg/predicate/predicate_suite_test.go
  pkg/predicate/predicate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#66 Rename application package to builder
  pkg/builder/build.go
  pkg/builder/build_test.go
  pkg/builder/builder_suite_test.go
  pkg/builder/doc.go
  pkg/builder/example_test.go
  pkg/patterns/application/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/L
