Repository kubernetes-sigs/controller-runtime, pull requests merged in 2018-11, with the labels that each got.

#132 Add prometheus metrics to internal controller
  Gopkg.lock
  Gopkg.toml
  pkg/builder/builder_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/controller_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/controller/metrics/metrics.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
  pkg/metrics/doc.go
  pkg/metrics/listener.go
  pkg/metrics/registry.go
  vendor/github.com/prometheus/client_golang/AUTHORS.md
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/fnv.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/untyped.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#178 do not hold the lock after controller has started
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#198 added process metrics and Go runtime metrics
  pkg/internal/controller/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#165 envtest: export DefaultKubeAPIServerFlags & make flags configurable
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#200 Refactor metrics tests
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#205 Cleanup duplicated words
  pkg/doc.go
  pkg/envtest/server.go
  pkg/webhook/internal/cert/provisioner.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#206 Fix typos: wehbook -> webhook
  pkg/webhook/internal/cert/writer/certwriter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#213 Add scheme support to fake client
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#212 Set GVK when getting the object from the cache.
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#220 Use typed lists in cert writer tests
  pkg/webhook/internal/cert/writer/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#216 :book: Versioning and Branching Strategy
  README.md
  VERSIONING.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#224 :running: PR Templates
  .github/PULL_REQUEST_TEMPLATE/breaking_change.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/compat_feature.md
  .github/PULL_REQUEST_TEMPLATE/docs.md
  .github/PULL_REQUEST_TEMPLATE/other.md
  VERSIONING.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#225 :running: Add default PR template
  .github/PULL_REQUEST_TEMPLATE/breaking_change.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/compat_feature.md
  .github/PULL_REQUEST_TEMPLATE/docs.md
  .github/PULL_REQUEST_TEMPLATE/other.md
  .github/pull_request_template.md
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#193 :bug: fix incorrect logr usage
  pkg/source/source.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#197 :bug: Serve metrics even if not leader
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/S
