Repository kubernetes-sigs/controller-runtime, pull requests merged in 2018-08, with the labels that each got.

#86 Clean up logging usage (and minor script improvements)
  .travis.yml
  example/main.go
  hack/check-everything.sh
  hack/common.sh
  hack/test-all.sh
  hack/verify.sh
  pkg/admission/cert/writer/certwriter.go
  pkg/admission/cert/writer/doc.go
  pkg/admission/cert/writer/fs.go
  pkg/admission/cert/writer/internal/atomic/atomic_writer.go
  pkg/admission/cert/writer/internal/atomic/atomic_writer_test.go
  pkg/admission/cert/writer/suite_test.go
  pkg/builder/builder_suite_test.go
  pkg/builder/example_test.go
  pkg/cache/cache_suite_test.go
  pkg/client/client_suite_test.go
  pkg/client/config/config.go
  pkg/client/fake/client.go
  pkg/client/fake/client_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/example_test.go
  pkg/envtest/envtest_suite_test.go
  pkg/envtest/server.go
  pkg/handler/eventhandler_suite_test.go
  pkg/internal/controller/controller_suite_test.go
  pkg/internal/recorder/recorder_suite_test.go
  pkg/manager/example_test.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
  pkg/predicate/predicate_suite_test.go
  pkg/reconcile/reconcile_suite_test.go
  pkg/runtime/log/deleg.go
  pkg/runtime/log/log.go
  pkg/runtime/log/log_test.go
  pkg/source/internal/internal_suite_test.go
  pkg/source/source_suite_test.go
  test.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#99 Fix duplicate controller references
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#104 Surface reconcile error in logs
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#109 Update OWNERS_ALIASES to fix approver bot
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S

#107 Clarify SyncPeriod comment
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#96 client: update status subresource support
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/split.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#81 admission webhook server
  Gopkg.lock
  example/controller.go
  example/main.go
  example/mutatingwebhook.go
  example/validatingwebhook.go
  pkg/admission/controller_test.go
  pkg/client/interfaces.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/patch/doc.go
  pkg/patch/patch.go
  pkg/webhook/admission/builder/builder.go
  pkg/webhook/admission/decode.go
  pkg/webhook/admission/doc.go
  pkg/webhook/admission/http.go
  pkg/webhook/admission/request.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/bootstrap.go
  pkg/webhook/cert/doc.go
  pkg/webhook/cert/generator/certgenerator.go
  pkg/webhook/cert/generator/certgenerator_test.go
  pkg/webhook/cert/generator/doc.go
  pkg/webhook/cert/generator/fake/certgenerator.go
  pkg/webhook/cert/generator/selfsigned.go
  pkg/webhook/cert/generator/selfsigned_test.go
  pkg/webhook/cert/provisioner.go
  pkg/webhook/cert/provisioner_test.go
  pkg/webhook/cert/writer/certwriter.go
  pkg/webhook/cert/writer/certwriter_test.go
  pkg/webhook/cert/writer/doc.go
  pkg/webhook/cert/writer/error.go
  pkg/webhook/cert/writer/fs.go
  pkg/webhook/cert/writer/fs_test.go
  pkg/webhook/cert/writer/internal/atomic/atomic_writer.go
  pkg/webhook/cert/writer/internal/atomic/atomic_writer_test.go
  pkg/webhook/cert/writer/multiple.go
  pkg/webhook/cert/writer/multiple_test.go
  pkg/webhook/cert/writer/secret.go
  pkg/webhook/cert/writer/secret_test.go
  pkg/webhook/cert/writer/suite_test.go
  pkg/webhook/doc.go
  pkg/webhook/server.go
  pkg/webhook/types/webhook.go
  vendor/github.com/mattbaird/jsonpatch/.gitignore
  vendor/github.com/mattbaird/jsonpatch/LICENSE
  vendor/github.com/mattbaird/jsonpatch/README.md
  vendor/github.com/mattbaird/jsonpatch/jsonpatch.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#115 move cert pkg to internal
  pkg/webhook/bootstrap.go
  pkg/webhook/internal/cert/doc.go
  pkg/webhook/internal/cert/generator/certgenerator.go
  pkg/webhook/internal/cert/generator/certgenerator_test.go
  pkg/webhook/internal/cert/generator/doc.go
  pkg/webhook/internal/cert/generator/fake/certgenerator.go
  pkg/webhook/internal/cert/generator/selfsigned.go
  pkg/webhook/internal/cert/generator/selfsigned_test.go
  pkg/webhook/internal/cert/provisioner.go
  pkg/webhook/internal/cert/provisioner_test.go
  pkg/webhook/internal/cert/writer/atomic/atomic_writer.go
  pkg/webhook/internal/cert/writer/atomic/atomic_writer_test.go
  pkg/webhook/internal/cert/writer/certwriter.go
  pkg/webhook/internal/cert/writer/certwriter_test.go
  pkg/webhook/internal/cert/writer/doc.go
  pkg/webhook/internal/cert/writer/error.go
  pkg/webhook/internal/cert/writer/fs.go
  pkg/webhook/internal/cert/writer/fs_test.go
  pkg/webhook/internal/cert/writer/multiple.go
  pkg/webhook/internal/cert/writer/multiple_test.go
  pkg/webhook/internal/cert/writer/secret.go
  pkg/webhook/internal/cert/writer/secret_test.go
  pkg/webhook/internal/cert/writer/suite_test.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#117 glog elimination round 2
  Gopkg.lock
  Gopkg.toml
  pkg/internal/admission/http.go
  pkg/internal/recorder/recorder.go
  pkg/internal/recorder/recorder_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  vendor/github.com/mitchellh/mapstructure/go.mod
  vendor/golang.org/x/sys/unix/syscall_freebsd.go
  vendor/golang.org/x/sys/unix/zsyscall_freebsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_freebsd_arm.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/mutating/dispatcher.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/request/admissionreview.go
  vendor/k8s.io/apiserver/pkg/admission/plugin/webhook/validating/dispatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#121 Add license headers to go files
  pkg/admission/controller_test.go
  pkg/builder/build_test.go
  pkg/builder/builder_suite_test.go
  pkg/client/apiutil/apimachinery.go
  pkg/controller/controllerutil/controllerutil_suite_test.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/envtest/envtest_test.go
  pkg/runtime/log/deleg.go
  pkg/runtime/log/log.go
  pkg/runtime/log/null.go
  pkg/runtime/scheme/scheme_suite_test.go
  pkg/runtime/scheme/scheme_test.go
  pkg/runtime/signals/signal.go
  pkg/runtime/signals/signal_posix.go
  pkg/runtime/signals/signal_windows.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#122 External clusters in envtest
  pkg/envtest/ginkgo.go
  pkg/envtest/printer/ginkgo.go
  pkg/envtest/server.go
  pkg/runtime/log/log_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#123 add tests for webhook/admission pkg
  pkg/webhook/admission/admission_suite_test.go
  pkg/webhook/admission/decode_test.go
  pkg/webhook/admission/http.go
  pkg/webhook/admission/http_test.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/response_test.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/admission/webhook_test.go
  pkg/webhook/types/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#126 gas linter renamed to gosec
  hack/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
