Repository kubernetes-sigs/controller-runtime, pull requests merged in 2018-07, with the labels that each got.

#69 Link to documentation from README.md
  README.md
  pkg/controller/example_test.go
  pkg/manager/example_test.go
Labels: cncf-cla: yes, size/M

#71 fix vendor logr
  Gopkg.lock
  Gopkg.toml
  pkg/runtime/log/deleg.go
  pkg/runtime/log/log.go
  pkg/runtime/log/log_test.go
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/examples/tab_logger.go
  vendor/github.com/go-logr/logr/examples/usage_example.go
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/go-logr/logr/testing/null.go
  vendor/github.com/go-logr/logr/testing/test.go
  vendor/github.com/go-logr/zapr/.gitignore
  vendor/github.com/go-logr/zapr/Gopkg.lock
  vendor/github.com/go-logr/zapr/Gopkg.toml
  vendor/github.com/go-logr/zapr/LICENSE
  vendor/github.com/go-logr/zapr/README.md
  vendor/github.com/go-logr/zapr/zaplogr.go
  vendor/github.com/thockin/logr/impls/zaplogr/zaplogr.go
  vendor/github.com/thockin/logr/logr.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#73 Fix un-initialized once that causes panic
  pkg/admission/controller.go
  pkg/admission/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#75 Minor changes to doc links in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#74 validate cert
  pkg/admission/cert/writer/certwriter.go
  pkg/admission/cert/writer/certwriter_test.go
  pkg/admission/cert/writer/fs_test.go
  pkg/admission/cert/writer/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#78 fix vendor zapr
  Gopkg.lock
  pkg/runtime/log/log.go
  vendor/github.com/go-logr/zapr/zapr.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#80 fix controllerutil_test
  pkg/admission/cert/writer/secret.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/source/internal/internal_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#84 config: fix using the KUBECONFIG to build the client
  pkg/client/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#82 Avoid adding test flags when using the null logger
  pkg/runtime/log/log.go
  pkg/runtime/log/null.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#91 Remove kube-aggregator from Gopkg.toml
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#88 Add a resync option to manager options
  pkg/cache/cache.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/S
