Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-10, with the labels that each got.

#625 :sparkles: Avoid extra deep copy in CacheReader.List
  go.mod
  pkg/cache/internal/cache_reader.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#622 🐛Prevent NewDiscoveryRESTMapper from panicking by calling NewDiscoveryClientForConfig
  pkg/client/apiutil/apimachinery.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#632 :book: Fix links in VERSIONING.md
  VERSIONING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#599 ✨ Bump dependencies for Kubernetes 1.15.4
  CONTRIBUTING.md
  go.mod
  go.sum
  hack/check-everything.sh
  hack/ci-check-everything.sh
  pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#627 :bug: Return error when trying to read from an unstarted cache
  pkg/cache/informer_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
  pkg/controller/controller_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#554 :warning: DynamicRESTMapper that reloads on REST cache miss
  go.mod
  go.sum
  hack/test-all.sh
  pkg/cache/cache_test.go
  pkg/client/apiutil/apiutil_suite_test.go
  pkg/client/apiutil/dynamicrestmapper.go
  pkg/client/apiutil/dynamicrestmapper_test.go
  pkg/internal/controller/controller_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/reconcile/reconciletest/reconcile.go
  pkg/source/source_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL

#634 :running: Tolerate merge commits in the release notes script
  hack/release/release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#635 :ghost: Don't do lazy discovery by default
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#419 ✨ added health probes
  pkg/healthz/doc.go
  pkg/healthz/healthz.go
  pkg/healthz/healthz_suite_test.go
  pkg/healthz/healthz_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, ok-to-test, size/XL

#643 :bug: Fix comments for option in zap
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#618 :warning: Bump to kube-1.16.0
  go.mod
  go.sum
  pkg/client/apiutil/apimachinery.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#646 :sparkles: Add helpers for common Zap options
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#545 ✨ implement helpers for add/remove finalizer
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#439 ✨ Improve webhook loggings
  pkg/webhook/admission/http.go
  pkg/webhook/admission/http_test.go
  pkg/webhook/admission/webhook_test.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#651 :bug: prevent controller.New and manager's errChan from leaking goroutines
  pkg/builder/controller_test.go
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
