Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-06, with the labels that each got.

#462 :ghost: add webhook markers in the example
  examples/crd/pkg/resource.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#465 :running: use :ghost: for no release note commits
  VERSIONING.md
  hack/release/common.sh
  hack/release/release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#473 :sparkles: Update Kubernetes to 1.13.4 [release-0.1]
  Gopkg.lock
  Gopkg.toml
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/codec.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
  vendor/k8s.io/client-go/transport/token_source.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#474 :running: Verify Emoji with GH actions
  .github/main.workflow
  hack/release/Dockerfile
  hack/release/common.sh
  hack/release/verify-emoji.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#466 🐛 Fix runnable race in manager
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#475 :ghost: ff release-0.2 branch to master
  .github/main.workflow
  CONTRIBUTING.md
  Gopkg.lock
  VERSIONING.md
  examples/builtins/main.go
  examples/crd/pkg/resource.go
  hack/release/Dockerfile
  hack/release/common.sh
  hack/release/release-notes.sh
  hack/release/verify-emoji.sh
  pkg/builder/build.go
  pkg/controller/controller.go
  pkg/doc.go
  pkg/envtest/server.go
  pkg/handler/doc.go
  pkg/internal/controller/controller.go
  pkg/manager/internal.go
  pkg/manager/manager_test.go
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
  pkg/webhook/internal/certwatcher/certwatcher.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#437 🐛 remove deprecated workqueue metrics with invalid names
  pkg/metrics/client_go_adapter.go
  pkg/metrics/workqueue.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#398 🐛Pass appropriate context to leaderelector.Run
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#463 :warning: make UseExistingCluster a pointer to support explicitly op…
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#482 :book: minor updates to the examples
  examples/builtins/main.go
  examples/builtins/mutatingwebhook.go
  examples/builtins/validatingwebhook.go
  examples/crd/pkg/resource.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/S

#486 :bug: stop registering webhooks with same path when adding multiple controllers
  pkg/builder/build.go
  pkg/builder/build_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#494 :sparkles: Fix runtime/scheme type aliases
  pkg/runtime/scheme/scheme.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#499 🐛 update jsonpatch
  Gopkg.lock
  go.mod
  go.sum
  pkg/webhook/admission/multi.go
  pkg/webhook/admission/multi_test.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/response_test.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/admission/webhook_test.go
  pkg/webhook/alias.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#497 :warning: split the webhook builder out as a separate builder.
  alias.go
  examples/crd/main.go
  go.sum
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/example_webhook_test.go
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#504 :sparkles: enable conversion webhook in webhook builder
  examples/conversion/pkg/apis/addtoscheme_jobs_v1.go
  examples/conversion/pkg/apis/addtoscheme_jobs_v2.go
  examples/conversion/pkg/apis/apis.go
  examples/conversion/pkg/apis/jobs/v1/register.go
  examples/conversion/pkg/apis/jobs/v2/register.go
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
  pkg/manager/internal.go
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
  pkg/webhook/conversion/testdata/.gitignore
  pkg/webhook/conversion/testdata/Makefile
  pkg/webhook/conversion/testdata/PROJECT
  pkg/webhook/conversion/testdata/api/v1/externaljob_types.go
  pkg/webhook/conversion/testdata/api/v1/groupversion_info.go
  pkg/webhook/conversion/testdata/api/v1/zz_generated.deepcopy.go
  pkg/webhook/conversion/testdata/api/v2/externaljob_types.go
  pkg/webhook/conversion/testdata/api/v2/groupversion_info.go
  pkg/webhook/conversion/testdata/api/v2/zz_generated.deepcopy.go
  pkg/webhook/conversion/testdata/api/v3/externaljob_types.go
  pkg/webhook/conversion/testdata/api/v3/groupversion_info.go
  pkg/webhook/conversion/testdata/api/v3/zz_generated.deepcopy.go
  pkg/webhook/conversion/testdata/hack/boilerplate.go.txt
  pkg/webhook/conversion/testdata/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#496 ✨ Fix typo
  .gitignore
  pkg/client/client_test.go
  pkg/client/options.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#487 :bug: fix runnable run twice issue
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#489 :sparkles: add GetConfigWithContext to retrieve a config with a specific context
  Gopkg.lock
  pkg/client/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#508 :bug: IsConvertible should not error on uninitialized struct.
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
