Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-12, with the labels that each got.

#701 📖: improve MultiNamespacedCacheBuilder info
  pkg/cache/multi_namespace_cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#698 📖 Remove obsolete cert provisioner docs
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#700 :running: Change the golint install to do it as recommended
  CONTRIBUTING.md
  Makefile
  hack/check-everything.sh
  hack/ci-check-everything.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#704 🐛 use semantic equality in CreateOrUpdate
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#689 :running: Add shawn-hurley as reviewer
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#690 :running: Add alvaroaleman as reviewer
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#707 :bug: Fix SetControllerReference to consider multiple CRD versions
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#706 ✨ envtest: surface merged crds
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#693 Add gerred as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#647 :sparkles: add 10% jitter to ResyncPeriod
  pkg/cache/cache.go
  pkg/cache/internal/informers_map.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#709 :running: Add joelanford as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#710 :sparkles: more visibility of the testing control plane
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#697 :sparkles: Clean-up installed CRDs on Stop()
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#719 :bug: Remove TotalRequests Prometheus metrics as it is not getting used
  pkg/webhook/internal/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#716 :sparkles: CRD file path on CRDInstallOptions.Paths
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#715 :sparkles: ErrorIfCRDPathMissing on Environment
  pkg/envtest/envtest_test.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#713 ✨ Define metrics.Registry as an interface
  pkg/metrics/registry.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#708 :bug: Envtest: Allow creating objects with privileged container specs
  pkg/controller/controller_integration_test.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
