Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-05, with the labels that each got.

#409 Add back http2 support :bug:
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#411 Replace github.com/ghodss/yaml with sigs.k8s.io/yaml 🏃
  Gopkg.lock
  Gopkg.toml
  pkg/envtest/crd.go
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#400 :sparkles: use more reasonable status code for ValidationResponse
  pkg/builder/build_test.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/response_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#351 :sparkles: crd conversion webhook implementation
  Gopkg.lock
  examples/conversion/pkg/apis/addtoscheme_jobs_v1.go
  examples/conversion/pkg/apis/addtoscheme_jobs_v2.go
  examples/conversion/pkg/apis/apis.go
  examples/conversion/pkg/apis/jobs/group.go
  examples/conversion/pkg/apis/jobs/v1/doc.go
  examples/conversion/pkg/apis/jobs/v1/externaljob_types.go
  examples/conversion/pkg/apis/jobs/v1/register.go
  examples/conversion/pkg/apis/jobs/v1/zz_generated.deepcopy.go
  examples/conversion/pkg/apis/jobs/v2/doc.go
  examples/conversion/pkg/apis/jobs/v2/externaljob_types.go
  examples/conversion/pkg/apis/jobs/v2/register.go
  examples/conversion/pkg/apis/jobs/v2/zz_generated.deepcopy.go
  pkg/conversion/conversion.go
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_suite_test.go
  pkg/webhook/conversion/conversion_test.go
  pkg/webhook/conversion/decoder.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#397 ✨ envtest can load multiple CRDs from single file
  Gopkg.lock
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/multiplecrds.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#418 🏃 task: enable running tests in prow
  hack/check-everything.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#410 :bug: Enable labels list options in fake client
  pkg/cache/internal/cache_reader.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/internal/objectutil/filter.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#396 :bug: Reset Failure count for reconcile loops using RequestAfter
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#423 :running: fix expect statement in conversion tests to be idiomatic
  pkg/webhook/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#425 :bug: List requests should not pass a body.
  pkg/client/typed_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#426 :bug: List requests should not pass a body.
  pkg/client/typed_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#431 :bugfix: support multiversion CRD in envtest
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/testdata/example_multiversion_crd1.yaml
  pkg/envtest/testdata/examplecrd1.yaml
  pkg/envtest/testdata/examplecrd2.yaml
  pkg/envtest/testdata/multiplecrds.yaml
  pkg/envtest/testdata/notcrd.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#432 :sparkles: stop allowing port 0
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#389 :bug: Populate GVK for listed objects
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#376 ⚠ Bump Kubernetes version to 1.14
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
  hack/check-everything.sh
  pkg/client/client_test.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
  pkg/leaderelection/leader_election.go
  pkg/metrics/client_go_adapter.go
  pkg/scheme/scheme_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/auth, size/L

#427 :sparkles: enable conversion webhook by default
  examples/conversion/pkg/apis/jobs/v1/register.go
  examples/conversion/pkg/apis/jobs/v2/register.go
  pkg/builder/build.go
  pkg/manager/internal.go
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#412 Make leader election lease duration configurable through manager options
  example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#424 support HA (non leader election) components
  examples/crd/pkg/groupversion_info.go
  examples/crd/pkg/resource.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#326 :bug: Ensure that enqueuemapped's mapper gets deps
  pkg/handler/enqueue_mapped.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#428 ✨ Implement `IgnoreNotFound`
  pkg/client/client_test.go
  pkg/client/interfaces.go
Labels: approved, cncf-cla: yes, size/M

#435 :warning: Minimal Apply Support, Fix Up Client Options
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/interfaces.go
  pkg/client/options.go
  pkg/client/patch.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#421 ✨ webhook: Handle TLS certificate rotation
  Gopkg.lock
  pkg/webhook/internal/certwatcher/certwatcher.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#441 :sparkles: webhook server doesn't use leader election by default
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#434 📖 Fix docs & comments referring to "Reconciler" instead of "reconcile"
  examples/builtins/main.go
  pkg/controller/controller.go
  pkg/doc.go
  pkg/handler/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#443 :bug: set status in conversion response
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#438 📖 (:book:, docs) Update contributing.md to use golangci-lint
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#448 :bug: update internal controller for more clean code and metrics
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#449 :sparkles: Allow setting "UseExistingCluster" via environment
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#458 :sparkles: Allow setting controller name, fix default
  pkg/builder/build.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#404 :running: support release notes on new version
  hack/release/common.sh
  hack/release/release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#459 :sparkles: more visibility of the testing control plane
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M
