Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-11, with the labels that each got.

#642 :sparkles: Add support for multi-value KUBECONFIG
  pkg/client/config/config.go
  pkg/client/config/config_suite_test.go
  pkg/client/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#653 :bug: pkg/log/zap: use enabled in UseDevMode, add tests
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#670 :bug: Allow kube-apiserver to start without a default route
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#672 ✨ Update sigs.k8s.io/testing_frameworks to v0.1.2
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#624 📖 Document environment variables supported by envtest
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/S

#662 :bug: pkg/metrics/workqueue.go: remove deprecated metrics
  pkg/metrics/workqueue.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#620 ✨ fakeClient: bump ResourceVersion on write
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#639 ✨ Add helpers for remaining Zap options
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#682 :sparkles:handle unstructured objects correctly in fake client
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/fake/doc.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#683 :ghost:add apiversion handling to fake client
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#679 :bug: go.mod,go.sum: revert prometheus/client_golang to v0.9.x
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#674 🐛 Fix delete example not setting metadata properly for CRDs
  pkg/client/example_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#675 🐛 cross-namespace owner references should be disallowed
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#678 :bug: InformerCache: Do not require leader lease
  pkg/cache/informer_cache.go
  pkg/cache/informer_cache_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#659 :sparkles: envtest set service-cluster-ip-range if user not set
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#685 :warning: Soft-bump to Go 1.13
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/XS
