Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-01, with the labels that each got.

#272 :bug: fix `nil` error when using `BootstrapOptions.Host`
  pkg/webhook/bootstrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#280 :bug: fix interface assertions in example/mutatingwebhook.go such that podA…
  example/mutatingwebhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#288 :bug: gen cert for the server even there are no webhooks
  pkg/webhook/internal/cert/provisioner.go
  pkg/webhook/internal/cert/provisioner_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#287 :sparkles: Fix up error reporting and logging in envtest
  pkg/envtest/crd.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#289 :bug: switch to use appscode/jsonpatch
  Gopkg.lock
  pkg/patch/patch.go
  pkg/webhook/admission/response_test.go
  pkg/webhook/admission/types/types.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/admission/webhook_test.go
  vendor/github.com/appscode/jsonpatch/.gitignore
  vendor/github.com/appscode/jsonpatch/.travis.yml
  vendor/github.com/appscode/jsonpatch/LICENSE
  vendor/github.com/appscode/jsonpatch/README.md
  vendor/github.com/appscode/jsonpatch/go.mod
  vendor/github.com/appscode/jsonpatch/go.sum
  vendor/github.com/appscode/jsonpatch/jsonpatch.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#233 :sparkles: Expose client-go metrics
  Gopkg.lock
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/controller/metrics/metrics.go
  pkg/metrics/client_go_adapter.go
  pkg/source/source_integration_test.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/L

#294 :warning: Convert client.List to use functional options
  pkg/builder/example_test.go
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/example_test.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/interfaces.go
  pkg/client/split.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
  pkg/webhook/internal/cert/writer/secret_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#274 :bug: EnqueueRequestForOwner correctly enqueue cluster-scoped owner
  Gopkg.lock
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler_suite_test.go
  pkg/handler/eventhandler_test.go
  pkg/manager/internal.go
  pkg/runtime/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#260 :bug: fix issue when webhook server refreshing cert
  Gopkg.lock
  pkg/webhook/server.go
  pkg/webhook/server_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#256 :warning: introduce PatchResponseFromRaw and drop PatchResponse
  example/mutatingwebhook.go
  pkg/patch/doc.go
  pkg/patch/patch.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/response_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#304 :bug: update call to ZapLoggerTo after refactor
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#298 :sparkles: Master -> Control Plane
  pkg/client/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S
