Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-09, with the labels that each got.

#582 :book: fix spelling of function EnqueueRequestsFromMapFunc
  pkg/doc.go
  pkg/handler/eventhandler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#579 :book: Update example dir in godoc
  pkg/doc.go
Labels: approved, cncf-cla: yes, kind/flake, lgtm, size/XS

#581 :running: Add script to run tests in Prow
  hack/ci-check-everything.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#584 :bug: Minor upgrade of gnostic to v0.3.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#578 :sparkles: pkg/client/options.go: MatchingSelector can add a fields.Selector to ListOptions
  pkg/client/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#596 :running: Release v0.2.1
  go.mod
  go.sum
  hack/ci-check-everything.sh
  pkg/client/options.go
  pkg/doc.go
  pkg/handler/eventhandler.go
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#591 :sparkles: Let users specify their own EventBroadcaster for the manager
  pkg/internal/recorder/recorder.go
  pkg/internal/recorder/recorder_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#589 :sparkles: Client option types implement client option interfaces
  Gopkg.lock
  pkg/client/options.go
  pkg/client/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#569 should support webhook certDir args
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#604 :running: Make the release notes script tolerant of merges
  hack/release/release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#593 :running: Remove travis.yaml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#605 :Running: Release v0.2.2
  .travis.yml
  Gopkg.lock
  hack/release/release-notes.sh
  pkg/client/options.go
  pkg/client/options_test.go
  pkg/internal/recorder/recorder.go
  pkg/internal/recorder/recorder_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#598 :warning: Remove dep usage and Gopkg.*
  CONTRIBUTING.md
  Gopkg.lock
  Gopkg.toml
  hack/check-everything.sh
  hack/ci-check-everything.sh
  hack/verify.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#544 :sparkles: Expose CRDInstallOptions via envtest.Environment
  pkg/builder/builder_suite_test.go
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#341 ✨ Add Limit and Continue functional list options for client
  pkg/client/client_test.go
  pkg/client/options.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#608 🐛 Set limit and continue in ApplyToList method
  pkg/client/options.go
  pkg/client/options_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S
