Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-04, with the labels that each got.

#380 🐛Fix used scheme for fake client in List method
  pkg/client/fake/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#363 :book: Fix a dead link to examples
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#383 :warning: source: make the Informer source compatible with cache.Informer
  pkg/source/source.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#232 :bug: Panic instead of Exit in FakeClient
  pkg/client/fake/client.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/S

#375 :bug: Remove redundant check
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#371 :bug: Ensure returned informers are always correctly synced
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#382 :sparkles: support custom negotiated serializer :bug:
  pkg/client/apiutil/apimachinery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#378 🐛 Add mutex to loggerPromise to prevent races
  pkg/log/deleg.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#402 📖 Update broken FAQ link
  doc.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
