Repository kubernetes-sigs/controller-runtime, pull requests merged in 2019-07, with the labels that each got.

#510 :warning: metrics are now on by default
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/metrics/listener.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#512 :running: ff release-0.2 branch to master HEAD
  Gopkg.lock
  pkg/client/config/config.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/metrics/listener.go
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#515 :bug: Remove unused disableWebhookConfigInstaller flag
  examples/builtins/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#513 :running: fix various typos
  FAQ.md
  TMP-LOGGING.md
  VERSIONING.md
  doc.go
  examples/builtins/controller.go
  pkg/builder/builder_suite_test.go
  pkg/builder/webhook.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
  pkg/client/client.go
  pkg/client/example_test.go
  pkg/client/patch.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/leaderelection/leader_election.go
  pkg/manager/manager.go
  pkg/metrics/client_go_adapter.go
  pkg/runtime/inject/inject_test.go
  pkg/runtime/log/log.go
  pkg/webhook/admission/webhook_test.go
  pkg/webhook/internal/certwatcher/certwatcher.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#522 :book: Note on Manager#GetClient about delegating clients
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#529 :sparkles: decoder now errors out when encountering an empty runtime.RawExtension
  pkg/webhook/admission/decode.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#525 :warning: support delete validation in validator interface
  examples/crd/pkg/resource.go
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
  pkg/webhook/admission/validator.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#530 :bug: stop using hardcoded temp dir
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#536 :warning: Functional Options Redux
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/multi_namespace_cache.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/doc.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/options.go
  pkg/client/split.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#539 🐛 fix grammer of error in SetControllerReference
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#519 :running: Only log CRD name during installation
  pkg/envtest/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#527 :book: Examples README
  examples/README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#447 ✨ Implement delete collection via delete options
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/example_test.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/interfaces.go
  pkg/client/options.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#528 :bug: Preserve GroupVersionKind during Update/Patch
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
