Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-06, with the labels that each got.

#951 📖 provide example of client.Patch
  pkg/client/example_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#975 🐛 Always shutdown etcd when stopping envtest
  pkg/internal/testing/integration/control_plane.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#944 :sparkles: Add webhook total and in-flight metrics
  pkg/webhook/internal/metrics/metrics.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#987 📖 Nit: improve doc string
  pkg/runtime/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#940 :running: Remove unused attributes from controller
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1000 :sparkles: Add ContainsFinalizer helper to the controllerutil
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#997 :running: Move pwittrock from emeritus approvers to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1002 :bug: cannot specify ControlPlane in envtest.Environment
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1010 [0.6] Update go.mod dependencies patch versions (v0.18.4)
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1009 [0.5] Update go.mod dependencies patch versions (v0.17.7)
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1003 🏃 Cleanup controller internal logger
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1008 🏃 Clarify log line in apiutil.GVKForObject
  pkg/client/apiutil/apimachinery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#985 🏃 Update json-patch dependency to e83c0a1c26c8
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1014 Prepare for v0.5.7
  go.mod
  go.sum
  pkg/client/apiutil/apimachinery.go
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/testing/integration/control_plane.go
  pkg/runtime/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1016 :bug: Fix webhook example
  pkg/webhook/example_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S
