Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-02, with the labels that each got.

#777 🏃 (:running:, other) Try to stabilize the flaky process_test
  pkg/internal/testing/integration/internal/process_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#763 ✨ (:sparkles, minor) APIServer defaults deduplication
  pkg/envtest/server.go
  pkg/internal/testing/integration/internal/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#446 :warning: Remove defaulting for leader election ID
  pkg/leaderelection/leader_election.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#790 📖: Add note about split client cache inconsistency
  doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#720 :warning: Envtest: Do not pull in ginkgo outside of _test.go files
  pkg/builder/builder_suite_test.go
  pkg/cache/cache_suite_test.go
  pkg/client/apiutil/apiutil_suite_test.go
  pkg/client/client_suite_test.go
  pkg/client/fake/client_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/envtest/ginkgo_test.go
  pkg/handler/eventhandler_suite_test.go
  pkg/healthz/healthz_suite_test.go
  pkg/internal/controller/controller_suite_test.go
  pkg/internal/recorder/recorder_suite_test.go
  pkg/manager/manager_suite_test.go
  pkg/manager/signals/signals_suite_test.go
  pkg/predicate/predicate_suite_test.go
  pkg/reconcile/reconcile_suite_test.go
  pkg/runtime/inject/inject_suite_test.go
  pkg/source/internal/internal_suite_test.go
  pkg/source/source_suite_test.go
  pkg/webhook/admission/admission_suite_test.go
  pkg/webhook/conversion/conversion_suite_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#606 :warning: Bump to Go 1.13
  hack/check-everything.sh
  hack/ci-check-everything.sh
  pkg/client/apiutil/dynamicrestmapper.go
  pkg/client/apiutil/dynamicrestmapper_test.go
  pkg/client/fake/client.go
  pkg/envtest/server.go
  pkg/internal/recorder/recorder.go
  pkg/leaderelection/leader_election.go
  pkg/metrics/listener.go
  pkg/webhook/admission/multi.go
  pkg/webhook/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, size/M

#738 :running: Verification of leak goroutine on controller and manager
  pkg/controller/controller_test.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#786 🐛 Integration test should close http body
  hack/verify.sh
  pkg/internal/testing/integration/internal/process.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#792 ✨Add HasLabels helper option for List calls
  pkg/client/fake/client_test.go
  pkg/client/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#795 :warning: Update dependencies to k8s 1.17
  go.mod
  go.sum
  pkg/internal/recorder/recorder_test.go
  pkg/leaderelection/fake/leader_election.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#793 🏃 (:running:, other) Bigger teardown timeout for flaky test
  pkg/envtest/envtest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#753 :bug: When loading client config, check os/user.HomeDir if $HOME is unset
  pkg/client/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#794 ✨ Create a supported way of setting a cache on source.Kind
  pkg/source/source.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#791 Add vincepri to maintainers
  OWNERS
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#756 :sparkles: support restconfig to target the control plane
  pkg/internal/testing/integration/control_plane.go
  pkg/internal/testing/integration/internal/integration_tests/integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#773 :running: Update linter and lint fixes
  .golangci.yml
  hack/check-everything.sh
  hack/verify.sh
  pkg/client/client_cache.go
  pkg/client/fake/client_test.go
  pkg/controller/controller_integration_test.go
  pkg/handler/eventhandler_test.go
  pkg/internal/controller/controller.go
  pkg/leaderelection/fake/leader_election.go
  pkg/log/zap/zap_test.go
  pkg/manager/internal.go
  pkg/manager/signals/signal_test.go
  pkg/reconcile/example_test.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#814 :bug: remove unused commented out testutil.go
  pkg/manager/testutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#815 🐛 Use GenerateName during fake client's Create method
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#809 ✨📖 Adding designs folder and sample template
  README.md
  designs/README.md
  designs/template.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#819 :running: prune any use of xerrors
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#796 🐛 Fix informer cache creating pointers to pointers
  pkg/cache/informer_cache.go
  pkg/cache/informer_cache_unit_test.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/controllertest/unconventionallisttypecrd.go
  pkg/controller/testdata/crds/unconventionallisttype.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#663 ✨ Take context when getting informer.
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#812 🐛 respect context in unstructured client
  pkg/client/client.go
  pkg/client/client_cache.go
  pkg/client/client_test.go
  pkg/client/codec.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: approved, cncf-cla: yes, lgtm, size/L
