Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-04, with the labels that each got.

#818 📖Adding ComponentConfig proposal
  designs/component-config.md
  designs/images/component-config-load.png
Labels: approved, cncf-cla: yes, lgtm, size/L

#882 :bug: MatchingLabels: Make sure requests with invalid labels fail
  pkg/client/options.go
  pkg/client/options_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#886 :warning: Fakeclient: reject create/update if Name isn't provided
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#885 :book: re-enable golangci-lint's godoc comment checking
  .golangci.yml
  pkg/builder/options.go
  pkg/builder/webhook.go
  pkg/client/fake/doc.go
  pkg/client/options.go
  pkg/controller/controllertest/unconventionallisttypecrd.go
  pkg/internal/testing/integration/internal/apiserver.go
  pkg/internal/testing/integration/internal/arguments.go
  pkg/internal/testing/integration/internal/etcd.go
  pkg/internal/testing/integration/internal/integration_tests/doc.go
  pkg/internal/testing/integration/internal/process.go
  pkg/internal/testing/integration/internal/tinyca.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#893 :running: Fix a typo in the error message
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#894 Adding docs using utilruntime.Must for scheme registration
  pkg/scheme/scheme.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#881 :bug: KubeAwareEncoder should handle unstructured object correctly
  pkg/log/zap/kube_helpers.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#905 🏃‍♂️ add apidiff.sh
  Makefile
  hack/apidiff.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#901 🏃 add alexeldeib as a reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#902 :bug: fix CRD filtering in envtest package
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#839 ✨ Add DryRunClient wrapper
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/dryrun_test.go
  pkg/client/options.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#848 ⚠ (:warning:, major) Do not disable admission plugins by default
  hack/check-everything.sh
  pkg/internal/testing/integration/internal/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#909 :bug: Ensure KUBECONFIG is unset when testing GetConfigWithContext
  pkg/client/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#906 :warning: log/zap options Level and StacktraceLevel type
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#913 :bug: Fix swapped constant value in webhook envtest
  pkg/envtest/webhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#910 🏃 don't use apidiff on dirty commits
  hack/apidiff.sh
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#824 ✨Expose metrics http server for extra endpoints
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#863 ✨Allow controllers to be started and stopped separately from the manager
  pkg/controller/controller.go
  pkg/controller/example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#917 :bug: controllerutil.RemoveFinalizer can occurs slice bounds out of range exception
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#883 :book: Correct Wrong Package Identifier in Explanation of EventHandler
  pkg/source/internal/eventsource.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#925 🏃 bump dependencies to v0.18.2
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#930 :sparkles: Manager: Export defaultNewClient
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#929 :bug: cannot specify ControlPlane in envtest.Environment
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
