Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-07, with the labels that each got.

#1037 feat:remove the whitelist word from our codebase
  pkg/envtest/crd.go
  pkg/envtest/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1038 feat:Remove master word from our codebase
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1041 🏃 [0.5] Update dependencies to v0.17.8
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1042 Prepare for v0.6.1
  OWNERS_ALIASES
  examples/builtins/controller.go
  go.mod
  go.sum
  pkg/client/apiutil/apimachinery.go
  pkg/client/client_test.go
  pkg/client/example_test.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/patch.go
  pkg/controller/controller.go
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/envtest/crd.go
  pkg/envtest/server.go
  pkg/envtest/webhook.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/testing/integration/control_plane.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/runtime/inject/inject.go
  pkg/source/source.go
  pkg/source/source_test.go
  pkg/webhook/example_test.go
  pkg/webhook/internal/certwatcher/certwatcher.go
  pkg/webhook/internal/metrics/metrics.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#981 🐛 Better UserAgent for leader-election client
  pkg/leaderelection/leader_election.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS, tide/merge-method-squash

#1012 🏃 Run tests with race detector enabled
  hack/test-all.sh
  pkg/builder/controller_test.go
  pkg/cache/informer_cache_unit_test.go
  pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
  pkg/internal/testing/integration/internal/process_test.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1045 Remove inactive members from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1047 :sparkles: optionally override leader election client config
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1043 ✨ pkg/predicate.go: add And and Or predicates
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1057 :running: Disable golangs parallel testing
  hack/test-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1059 :sparkles: Add IsZero method to reconcile.Result
  pkg/reconcile/reconcile.go
  pkg/reconcile/reconcile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#967 :sparkles: Implement graceful shutdown
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1022 🐛 Prefer reconciler from controller.Options
  pkg/builder/controller.go
  pkg/builder/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1061 Prepare for v0.5.9
  Makefile
  OWNERS_ALIASES
  hack/apidiff.sh
  hack/test-all.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  pkg/envtest/crd.go
  pkg/envtest/webhook.go
  pkg/leaderelection/leader_election.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
  pkg/reconcile/reconcile.go
  pkg/reconcile/reconcile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1062 :seedling: Remove -parallel flag from test coverage
  hack/test-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1067 :running: Make alvaroaleman approver
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1066 ✨ Implement NewPredicateFuncs to create predicate functions from a filter function
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#991 🐛 Fix allowed levels for --zap-log-levels flag to align with logr levels
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#1069 Remove coverage when running tests
  hack/test-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1070 Mark leak goroutine tests as pending
  pkg/controller/controller_test.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1065 ✨ Fix typo in envtest.Environment struct
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1072 🐛 Enable Logger Injection for Controller Manager
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1077 🐛 Test can inspect stdout & stderr: Give some time to exit
  pkg/internal/testing/integration/internal/process_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
