Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-05, with the labels that each got.

#938 :running: Remove unsed Config attribute from controller
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#919 🐛 Reset resource version if fake client Create call failed
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#941 ✨ Controller: Let sources sync even if they use a different cluster
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/source/source.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#898 ✨ Introduce controllerutil.Object interface
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#954 :bug: Fix scheme used by `DeleteAllOf` in fake client
  pkg/client/fake/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#955 Backports for v0.5.3
  pkg/client/config/config.go
  pkg/client/options.go
  pkg/client/options_test.go
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
  pkg/envtest/testdata/webhooks/manifests.yaml
  pkg/envtest/webhook.go
  pkg/envtest/webhook_test.go
  pkg/log/zap/kube_helpers.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#957 Backport release-0.5: Fix scheme used by `DeleteAllOf` in the fake client.
  pkg/client/fake/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#953 📖 Prevent errors to be logged multiple times in builtins example
  examples/builtins/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#922 :sparkles: Add ContainsFinalizer helper to the controllerutil
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#960 Backports for v0.5.4
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/source/source.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#962 :sparkles: Migrate controllerutil AddFinalizer and RemoveFinalizer to controllerutil.Object and deprecate *WithError functions
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#968 🐛 fix(dependency) Use github.com/fsnotify/fsnotify
  go.mod
  pkg/webhook/internal/certwatcher/certwatcher.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#969 :sparkles: Add Patch MergeFrom optimistic locking option
  pkg/client/client_test.go
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#973 [0.5] :sparkles: Add Patch MergeFrom optimistic locking option
  pkg/client/client_test.go
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/L
