Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-11, with the labels that each got.

#1238 🐛 Fix use of `UnstructuredList` with unregistered typed
  pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1242 :sparkles: Allow to use builder.OnlyMetadata option with Watches
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1244 ✨ ComponentConfig alias for cfg.File()
  alias.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1240 🌱 Remove duplicate lines in controller.go
  pkg/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1241 🌱 Use lowercase space separated keys
  alias.go
  pkg/builder/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1251 ✨ Updating Component Config error messages
  pkg/config/config.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1225 :bug: Ensure that webhook server is thread/start-safe
  pkg/builder/webhook_test.go
  pkg/envtest/webhook.go
  pkg/manager/internal.go
  pkg/webhook/server.go
  pkg/webhook/server_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1245 🌱 Add back error logging for Reconcile implementation
  TMP-LOGGING.md
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1248 ✨ Backport support for metadata-only watches to release-0.6
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/example_test.go
  pkg/builder/options.go
  pkg/cache/cache_test.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
  pkg/client/apiutil/apimachinery.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/metadata_client.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1254 ✨ Add predicate for annotations change on update event
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1253 ✨ rename GetControllerManagerConfiguration to Complete
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/example_test.go
  pkg/config/v1alpha1/types.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1259 :warning: Fakeclient: Allow to pass ObjectLists to constructors
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1249 ⚠Add ability for the delegating client to avoid caching objects
  pkg/client/client_test.go
  pkg/client/split.go
  pkg/manager/client_builder.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/runtime/inject/inject_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1269 :sparkles: Update k8s version in envtest
  hack/check-everything.sh
  hack/setup-envtest.sh
  pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1256 ✨ Backport release-0.5: Support metadata-only watches
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/example_test.go
  pkg/builder/options.go
  pkg/cache/cache_test.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
  pkg/client/apiutil/apimachinery.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/metadata_client.go
  pkg/handler/enqueue_owner.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1214 :sparkles: Allow passing the assets path bin via the env config
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1276 :bug: Wait for metadata cache to sync
  pkg/cache/internal/deleg_map.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1239 :book: fix minor typo for the GracefulShutdownTimeout field comments
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1273 :seedling: Specify buckets for "controller_runtime_reconcile_time_seconds" histogram metrics
  pkg/internal/controller/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1149 :warning: Use application/vnd.kubernetes.protobuf as content-type if possible
  pkg/cache/internal/informers_map.go
  pkg/client/apiutil/apimachinery.go
  pkg/client/client.go
  pkg/client/client_cache.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1277 🌱Use go-logr context functions
  go.mod
  go.sum
  pkg/log/log.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1279 :running: AddToProtobufScheme: Take AddToScheme, not Schemebulilder
  pkg/client/apiutil/apimachinery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
