Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-10, with the labels that each got.

#1116 ⚠️ Propagate context.Context throughout the codebase
  designs/move-cluster-specific-code-out-of-manager.md
  example_test.go
  examples/builtins/main.go
  examples/crd/main.go
  pkg/builder/controller_test.go
  pkg/builder/example_test.go
  pkg/builder/example_webhook_test.go
  pkg/builder/webhook_test.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
  pkg/cache/multi_namespace_cache.go
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_test.go
  pkg/controller/example_test.go
  pkg/envtest/webhook_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/manager/example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/scheme/scheme.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
  pkg/source/source_suite_test.go
  pkg/source/source_test.go
  pkg/webhook/conversion/testdata/main.go
  pkg/webhook/example_test.go
  pkg/webhook/internal/certwatcher/certwatcher.go
  pkg/webhook/server.go
  pkg/webhook/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1194 🌱 Expose handler.MapFunc to allow implementers to test mappers
  pkg/handler/enqueue_mapped.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#972 :sparkles: envtest utility, defaultable flags
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  examples/scratch-env/main.go
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, kind/feature, lgtm, size/XL

#1197 :seedling: Use kubebuilder-release-tools
  .github/main.workflow
  .github/workflows/verify.yml
  VERSIONING.md
  hack/release/Dockerfile
  hack/release/common.sh
  hack/release/release-notes.sh
  hack/release/verify-emoji.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1196 🐛 Controller reconcileHandler shouldn't stop a worker on error
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1195 ⚠ Introduce and use client.Object and client.ObjectList
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/webhook_test.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/cache/informer_cache_unit_test.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/multi_namespace_cache.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/example_test.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/object.go
  pkg/client/split.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/event/event.go
  pkg/handler/enqueue_mapped.go
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
  pkg/source/internal/eventsource.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1198 :book: Update versioning to reference common guidelines
  VERSIONING.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1199 :book: Be more specific about compat in VERSIONING
  VERSIONING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1202 🌱 Add ctrl.{LoggerFrom, LoggerInto}
  alias.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1204 :seedling: Add controller.GetLogger
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1206 :sparkles: Zap: Add JSONEncoder and ConsoleEncoder opts
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1205 :warning: Propagate context on Manager.Start(...)
  designs/move-cluster-specific-code-out-of-manager.md
  example_test.go
  examples/builtins/main.go
  examples/crd/main.go
  examples/scratch-env/main.go
  go.mod
  go.sum
  pkg/builder/controller_test.go
  pkg/builder/example_test.go
  pkg/builder/example_webhook_test.go
  pkg/builder/webhook_test.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_test.go
  pkg/envtest/webhook_test.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/manager/example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/signals/signal.go
  pkg/manager/signals/signal_test.go
  pkg/webhook/example_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1200 :seedling: Use client.Object interface in envtest
  pkg/envtest/crd.go
  pkg/envtest/envtest_suite_test.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
  pkg/envtest/server.go
  pkg/envtest/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1203 📖 Add more details for what's included in a logger
  alias.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1207 :warning: Handler: Remove MapObject type and use client.Object directly
  pkg/handler/enqueue_mapped.go
  pkg/handler/eventhandler_test.go
  pkg/handler/example_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1213 🐛 Tracker upgrade should use gvk from scheme
  pkg/client/fake/client.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1088 :sparkles: Add namespace enforcing wrapper for client.Client
  pkg/client/namespaced_client.go
  pkg/client/namespaced_client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XL, tide/merge-method-squash

#1224 :warning: client.ObjectKeyFromObject now uses client.Client
  pkg/client/interfaces.go
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1231 :book: Improve docs for client.Object
  pkg/client/object.go
Labels: approved, cncf-cla: yes, lgtm, size/M
