Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-12, with the labels that each got.

#1282 ✨ Backport release-0.6: Wait for metadata cache to sync
  pkg/cache/internal/deleg_map.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1283 ✨ Backport release-0.5: Wait for metadata cache to sync
  pkg/cache/internal/deleg_map.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1281 :sparkles: Add fake.NewClientBuilder to build new fake clients
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/runtime/inject/inject_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1284 :warning: pkg/webhook/admission: upgrade v1beta1 admission types to v1
  pkg/builder/webhook_test.go
  pkg/webhook/admission/decode_test.go
  pkg/webhook/admission/http.go
  pkg/webhook/admission/http_test.go
  pkg/webhook/admission/multi.go
  pkg/webhook/admission/multi_test.go
  pkg/webhook/admission/response.go
  pkg/webhook/admission/response_test.go
  pkg/webhook/admission/validator.go
  pkg/webhook/admission/validator_test.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/admission/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1286 🐛 client.List should check on UnstructuredList, not Unstructured
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1287 :bug: client.List should check on UnstructuredList, not Unstructured
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1288 🌱 Add test that checks List works on UnstructuredList not in Scheme
  pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1289 🐛 Inject manager's logger instead of internal one
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1293 :bug: pkg/webhook/admission: set GVK on AdmissionReview responses
  pkg/webhook/admission/http.go
  pkg/webhook/admission/http_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#1265 ✨ Support for using both an external control plane and automatic webhooks together
  pkg/builder/builder_suite_test.go
  pkg/envtest/webhook.go
  pkg/internal/testing/integration/addr/manager.go
  pkg/internal/testing/integration/addr/manager_test.go
  pkg/internal/testing/integration/apiserver.go
  pkg/internal/testing/integration/internal/process.go
  pkg/internal/testing/integration/internal/process_test.go
  pkg/internal/testing/integration/internal/tinyca.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1268 :sparkles: Bump k8s dependencies to 1.20
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1297 :bug: Cache bypass should take into account List types
  pkg/client/split.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1298 :bug: Cache bypass should take into account List types
  pkg/client/split.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1299 🐛 Do not set PatchType if patch is empty
  pkg/webhook/admission/response.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S
