Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-08, with the labels that each got.

#1092 🏃 setup-envtest.sh: standalone script for setting up envtest
  hack/check-everything.sh
  hack/common.sh
  hack/setup-envtest.sh
  hack/test-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1093 ✨ Add ability to set/get logger in/from a context.Context
  alias.go
  pkg/log/log.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1053 🏃 Generate junit in CI
  hack/test-all.sh
  pkg/builder/builder_suite_test.go
  pkg/cache/cache_suite_test.go
  pkg/client/apiutil/apiutil_suite_test.go
  pkg/client/client_suite_test.go
  pkg/client/config/config_suite_test.go
  pkg/client/fake/client_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/controller/controllerutil/controllerutil_suite_test.go
  pkg/envtest/envtest_suite_test.go
  pkg/envtest/printer/prow.go
  pkg/handler/eventhandler_suite_test.go
  pkg/healthz/healthz_suite_test.go
  pkg/internal/controller/controller_suite_test.go
  pkg/internal/recorder/recorder_suite_test.go
  pkg/internal/testing/integration/addr/addr_suite_test.go
  pkg/internal/testing/integration/integration_suite_test.go
  pkg/internal/testing/integration/internal/integration_tests/integration_suite_test.go
  pkg/internal/testing/integration/internal/internal_suite_test.go
  pkg/log/log_suite_test.go
  pkg/log/zap/zap_suite_test.go
  pkg/manager/manager_suite_test.go
  pkg/manager/signals/signals_suite_test.go
  pkg/predicate/predicate_suite_test.go
  pkg/reconcile/reconcile_suite_test.go
  pkg/runtime/inject/inject_suite_test.go
  pkg/scheme/scheme_suite_test.go
  pkg/source/internal/internal_suite_test.go
  pkg/source/source_suite_test.go
  pkg/webhook/admission/admission_suite_test.go
  pkg/webhook/conversion/conversion_suite_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1095 :sparkles: Add options to configure a logger for manager and controllers
  pkg/builder/controller.go
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1098 Update dependencies to Kubernetes v1.18.6
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1099 Update to Kuberentes v1.17.9
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1100 :sparkles: Make individual readiness and liveness checks accessible
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#989 🐛 Avoid marshalling error in debug log line
  pkg/webhook/admission/http.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1097 🏃 hack/setup-envtest.sh: follow-up from #1092
  hack/check-everything.sh
  hack/setup-envtest.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#1024 Change other/minor emoji for PRs to :seedling:
  .github/PULL_REQUEST_TEMPLATE/other.md
  .github/pull_request_template.md
  VERSIONING.md
  hack/release/common.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1039 ⚠️ Remove deprecated "--master" flag
  pkg/client/config/config.go
  pkg/client/config/config_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S, wg/naming

#1103 :warning: Remove deprecated client.ConstantPatch function
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1102 :warning: Remove deprecated For/WithConfig from controller builder
  pkg/builder/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1107 :warning: Remove deprecated pkg/runtime/scheme
  pkg/runtime/scheme/scheme.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1058 ⚠ Expose Client runtime.Scheme
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/example_test.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/split.go
  pkg/manager/manager.go
  pkg/runtime/inject/inject_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1068 Bump to Kubernetes 1.19-rc.3
  go.mod
  go.sum
  pkg/controller/controllertest/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1108 :warning: Remove deprecated pkg/runtime/signals package
  pkg/runtime/signals/signal.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1109 :warning: Expose RESTMapper on Client interface
  pkg/client/client.go
  pkg/client/dryrun.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/split.go
  pkg/runtime/inject/inject_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1111 Update module dependencies
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1106 :warning: Remove reconciletest deprecated package
  pkg/reconcile/reconciletest/reconcile.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1112 :warning: Remove deprecated pkg/client options
  pkg/client/client_test.go
  pkg/client/options.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1105 :warning: Remove deprecated pkg/runtime/log package and utils
  examples/builtins/main.go
  examples/crd/main.go
  examples/crd/pkg/groupversion_info.go
  pkg/builder/builder_suite_test.go
  pkg/cache/cache_suite_test.go
  pkg/client/apiutil/apiutil_suite_test.go
  pkg/client/client_suite_test.go
  pkg/client/config/config_suite_test.go
  pkg/client/fake/client_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/envtest/envtest_suite_test.go
  pkg/handler/eventhandler_suite_test.go
  pkg/healthz/healthz_suite_test.go
  pkg/internal/controller/controller_suite_test.go
  pkg/internal/log/log.go
  pkg/internal/recorder/recorder_suite_test.go
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
  pkg/manager/manager_suite_test.go
  pkg/predicate/predicate_suite_test.go
  pkg/reconcile/reconcile_suite_test.go
  pkg/runtime/log/log.go
  pkg/source/internal/internal_suite_test.go
  pkg/source/source_suite_test.go
  pkg/webhook/admission/admission_suite_test.go
  pkg/webhook/conversion/conversion_suite_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1104 :warning: Remove {Add,Remove}FinalizerWithError utils
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1054 ⚠ Add a context w/ logger to Reconciler interface
  example_test.go
  examples/builtins/controller.go
  examples/builtins/main.go
  examples/crd/main.go
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/example_test.go
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_test.go
  pkg/controller/example_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/reconcile/example_test.go
  pkg/reconcile/reconcile.go
  pkg/reconcile/reconcile_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1076 ⚠️ Change default webhook port to 9443
  pkg/builder/builder_suite_test.go
  pkg/manager/manager_test.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1080 ⚠️ Add support to read webhook configurations from files for WebhookInstallOptions
  pkg/envtest/webhook.go
  pkg/envtest/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1118 :warning: Use controllerutil.Object for event handling
  pkg/builder/controller_test.go
  pkg/event/event.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler_test.go
  pkg/handler/example_test.go
  pkg/predicate/example_test.go
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
  pkg/source/internal/eventsource.go
  pkg/source/internal/internal_test.go
  pkg/source/source_integration_test.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1096 ⚠️ Remove logs from internal controller
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1119 :sparkles: Simplify usage of EnqueueRequestsFromMapFunc
  pkg/handler/enqueue_mapped.go
  pkg/handler/eventhandler_test.go
  pkg/handler/example_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1121 ✨ Added the LabelSelectorPredicate function for filtering events
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#926 :bug: Fakeclient: Honor AllowUnconditionalUpdate and AllowCreateOnUpdate for resources that support it
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, size/L

#1126 :sparkles: Allow configuring LeaderElectionReleaseOnCancel
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1125 :sparkles: Add metrics for total workers and active workers
  pkg/internal/controller/controller.go
  pkg/internal/controller/metrics/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#915 ✨ Added Encoder Config Options field.
  go.mod
  go.sum
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1031 add a known limitations section to fake Client
  pkg/client/fake/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S, tide/merge-method-squash

#1089 Try to avoid event handling leaks
  go.mod
  go.sum
  pkg/controller/controller_suite_test.go
  pkg/controller/controller_test.go
  pkg/internal/recorder/recorder.go
  pkg/internal/recorder/recorder_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/L

#1134 :bug: Avoid the redirection to `/healthz/` when calling `/healthz`
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1137 🌱 [0.6] Update json-patch to v4.9.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1138 🌱 [0.5] Update json-patch to v4.9.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1136 :seedling: Update json-patch to v4.9.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1139 :bug: Controller: Return error when started more than once
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1141 :bug: Handle empty contexts in log.FromContext
  pkg/log/log.go
  pkg/log/log_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1129 :warning: admission responses with raw Status
  pkg/webhook/admission/response.go
  pkg/webhook/admission/validator.go
  pkg/webhook/admission/validator_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1145 :sparkles: Update k8s.io dependencies to v0.19.0
  Makefile
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1144 ⚠ Change leaderlock from ConfigMap to ConfigMapsLeasesResourceLock
  pkg/leaderelection/leader_election.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1146 :bug: Source.Channel: Cope with pre-existing events in the channel
  pkg/source/source.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
