Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-03, with the labels that each got.

#811 📖 document exposed metrics
  pkg/metrics/client_go_adapter.go
  pkg/metrics/listener.go
  pkg/metrics/workqueue.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#816 :sparkles: Add controllerutil.EnsureOwnerReference
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#821 🏃 Add verification tools, linter and modules
  .gitignore
  .golangci.yml
  Makefile
  go.mod
  go.sum
  hack/check-everything.sh
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/verify.sh
Labels: approved, cncf-cla: yes, lgtm, size/XL

#779 :running: Use scheme.Convert to convert unstructrured objects
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#829 Add shawn-hurley to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#731 ✨Make workqueue rate limiter configurable during controller creation
  pkg/builder/controller_test.go
  pkg/controller/controller.go
  pkg/ratelimiter/doc.go
  pkg/ratelimiter/ratelimiter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#802 ✨enable webhook server set-up mTLS service to verify client's certificate
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#787 ⚠ (:warning:, major) Webhook support in envtest
  pkg/cache/cache_test.go
  pkg/envtest/envtest_suite_test.go
  pkg/envtest/envtest_test.go
  pkg/envtest/server.go
  pkg/envtest/webhook.go
  pkg/envtest/webhook_test.go
  pkg/internal/testing/integration/apiserver.go
  pkg/internal/testing/integration/control_plane.go
  pkg/internal/testing/integration/internal/apiserver.go
  pkg/internal/testing/integration/internal/tinyca.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#843 🐛 Fix testdata imports in pkg/webhook/conversion
  pkg/webhook/conversion/testdata/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#823 📖 reference kubebuilder in README
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#844 🏃Rename EnsureOwnerReference to SetOwnerReference for consistency
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#767 ✨ Add helpers to configure logger options via pflags
  go.mod
  go.sum
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#846 🐛 expose DefaultKubeAPIServerFlags in envtest
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#859 🐛 fix conservative delay in rate limiter
  pkg/client/apiutil/dynamicrestmapper.go
  pkg/client/apiutil/dynamicrestmapper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#862 Add joelanford to approvers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#834 🏃fetch_ext_bins now checks existing version before downloading
  hack/check-everything.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#864 :running: Tolerate (more) merge commits in release notes
  hack/release/release-notes.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#865 :running: Release v0.5.2
  OWNERS_ALIASES
  go.mod
  go.sum
  hack/check-everything.sh
  hack/release/release-notes.sh
  pkg/client/apiutil/dynamicrestmapper.go
  pkg/client/apiutil/dynamicrestmapper_test.go
  pkg/envtest/server.go
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#861 🐛 fix version check when reading webhooks from file
  pkg/envtest/testdata/webhooks/manifests.yaml
  pkg/envtest/webhook.go
  pkg/envtest/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#877 📖 Fix a minor typo in the Reconciler docs
  pkg/reconcile/reconcile.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#832 :warning: Fakeclient: Reject Update with outdated ResourceVersion
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#799 :warning: Add predicates as variadic args for Owns, For, and Watches func
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/options.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#830 ⚠ update Informers interface to accept context
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/multi_namespace_cache.go
  pkg/client/example_test.go
  pkg/client/interfaces.go
  pkg/internal/controller/controller_test.go
  pkg/source/source.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#836 🏃 Bump dependencies for Kubernetes v1.18.0
  go.mod
  go.sum
  pkg/cache/internal/informers_map.go
  pkg/client/client_test.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
  pkg/controller/controller_integration_test.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/internal/testing/integration/internal/integration_tests/integration_test.go
  pkg/leaderelection/fake/leader_election.go
  pkg/metrics/client_go_adapter.go
  pkg/recorder/example_test.go
  pkg/source/source_integration_test.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XL

#842 🏃 Use whole list matching for known types.
  pkg/scheme/scheme_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
