Repository kubernetes-sigs/controller-runtime, pull requests merged in 2020-01, with the labels that each got.

#749 ⚠ Bring in testing framework
  OWNERS_ALIASES
  go.mod
  go.sum
  hack/check-everything.sh
  pkg/builder/builder_suite_test.go
  pkg/envtest/server.go
  pkg/internal/testing/OWNERS
  pkg/internal/testing/integration/.gitignore
  pkg/internal/testing/integration/README.md
  pkg/internal/testing/integration/addr/addr_suite_test.go
  pkg/internal/testing/integration/addr/manager.go
  pkg/internal/testing/integration/addr/manager_test.go
  pkg/internal/testing/integration/apiserver.go
  pkg/internal/testing/integration/assets/bin/.gitkeep
  pkg/internal/testing/integration/control_plane.go
  pkg/internal/testing/integration/doc.go
  pkg/internal/testing/integration/etcd.go
  pkg/internal/testing/integration/integration_suite_test.go
  pkg/internal/testing/integration/internal/apiserver.go
  pkg/internal/testing/integration/internal/apiserver_test.go
  pkg/internal/testing/integration/internal/arguments.go
  pkg/internal/testing/integration/internal/arguments_test.go
  pkg/internal/testing/integration/internal/bin_path_finder.go
  pkg/internal/testing/integration/internal/bin_path_finder_test.go
  pkg/internal/testing/integration/internal/etcd.go
  pkg/internal/testing/integration/internal/etcd_test.go
  pkg/internal/testing/integration/internal/integration_tests/apiserver_integration_test.go
  pkg/internal/testing/integration/internal/integration_tests/doc.go
  pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
  pkg/internal/testing/integration/internal/integration_tests/integration_suite_test.go
  pkg/internal/testing/integration/internal/integration_tests/integration_test.go
  pkg/internal/testing/integration/internal/internal_suite_test.go
  pkg/internal/testing/integration/internal/process.go
  pkg/internal/testing/integration/internal/process_test.go
  pkg/internal/testing/integration/kubectl.go
  pkg/internal/testing/integration/kubectl_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#747 📖 (nit) fix grammar and spelling typos
  Makefile
  TMP-LOGGING.md
  VERSIONING.md
  pkg/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#737 :sparkles: client: Use dynamic RESTMapper by default
  pkg/client/client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#746 :running: Minor nit in predicates
  pkg/predicate/predicate.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#739 📖Replace NullLogger with a zap logger in the ExampleBuilder
  pkg/builder/example_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#725 :running: Adding another folder with the CRD avoiding late deleted conflicts
  pkg/envtest/envtest_test.go
  pkg/envtest/testdata/crds/examplecrd3.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#744 :running: Remove usage of deprecated MatchingField list option
  pkg/cache/cache_test.go
  pkg/client/client_test.go
  pkg/client/example_test.go
  pkg/client/options.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#721 :sparkles: Add Merge patch type and deprecate ConstantPatch in favor of RawPatch
  pkg/client/client_test.go
  pkg/client/fake/client_test.go
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#742 📖 Rename "object" to "owned" to match godoc comment.
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#751 📖 docs: document the expected names of the TLS key and certificate
  pkg/manager/manager.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#696 :sparkles: update CRD if already present
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/testdata/crdv1_original/example_multiversion_crd1.yaml
  pkg/envtest/testdata/crdv1_updated/example_multiversion_crd1_one_more_version.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#755 :bug: wait for cache start before returning from WaitForCacheSync
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#762 📖 (:book:, docs) Remove references to 'download-binaries.sh'
  pkg/internal/testing/integration/assets/bin/.gitkeep
  pkg/internal/testing/integration/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#769 🏃 Update ginkgo@1.11.0 and gomega@1.8.1
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#760 :sparkles: Parameterize webhook key/cert name
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#766 📖 Fix error in doc
  pkg/builder/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#772 :running: Remove unused variable from IsConvertible
  pkg/webhook/conversion/conversion.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#752 ⚠ Add testenv support for CRDv1/CRDv1beta1 + update to k8s 1.16.4
  hack/check-everything.sh
  pkg/builder/builder_suite_test.go
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/helper.go
  pkg/envtest/server.go
  pkg/envtest/testdata/examplecrd.yaml
  pkg/envtest/testdata/examplecrd_v1.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#771 🏃 (:running:, other) Fix makefile and docs for running tests
  CONTRIBUTING.md
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#761 Add 'alenkacz' as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#783 :running: Add vincepri to reviewers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#784 :running: Clean up OWNERS file
  OWNERS
  OWNERS_ALIASES
  pkg/internal/testing/OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/M

#776 🏃 (:running:, other) Remove travis badge from readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#781 🐛 (:bug:, patch) Fix panic in call to processState.Stop()
  pkg/internal/testing/integration/apiserver.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#785 :book: update example to pass in the client
  examples/builtins/main.go
  examples/builtins/mutatingwebhook.go
  examples/builtins/validatingwebhook.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#774 🏃🏻‍♀️ Make gerred approver
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS
