Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-03, with the labels that each got.

#1402 :bug: [release-0.8]: Manager leader election: Don't reset restcfg UserAgent
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1401 :bug: Manager leader election: Don't reset restcfg UserAgent
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1400 :running: Builder: Remove unused restconfig attribute
  pkg/builder/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1408 :seedling: Update dependencies to v0.21.0-beta.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1399 ⚠ Handle finalizers in the fake client
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#1232 :book: Improve docs for manager.Options.SyncPeriod
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/rotten, size/S, tide/merge-method-squash

#1395 ⚠️ Change client.Patch to take client.Object for performance
  pkg/client/interfaces.go
  pkg/client/patch.go
  pkg/client/patch_test.go
  pkg/controller/controllerutil/controllerutil.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#1406 ✨ Add client.StrategicMergeFrom
  pkg/client/client_test.go
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1410 🐛 Fix client.Apply and client.Merge to satisfy Patch
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1413 :sparkles: [release-0.8] Add client.StrategicMergeFrom
  pkg/client/client_test.go
  pkg/client/patch.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1414 :book: Fix reference in comment
  pkg/cluster/cluster.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1415 :sparkles: [release-0.8]Revert injection deprecation logging
  pkg/cluster/cluster.go
  pkg/internal/controller/controller.go
  pkg/manager/internal.go
  pkg/runtime/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/S

#1302 :bug: Print webhook config options from scratch-env example
  examples/scratch-env/main.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1409 :warning: Allow setting NewClientFunc w/o implementing an interface
  pkg/cluster/client_builder.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/manager/client_builder.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1421 🌱 Update dependencies to v0.21.0-beta.1
  go.mod
  go.sum
  pkg/metrics/client_go_adapter.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1390 ✨ Deduplicate events before sending them into the workqueue.
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#1427 :bug: Controller: Wait for all reconciliations before shutting down
  pkg/controller/controller_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1430 :bug: Deflake should update CRDs if already present in the cluster
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1428 :bug: Fix cache sync timeout functionality
  pkg/internal/controller/controller_test.go
  pkg/source/source.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1434 🐛fix: fix the typo of `UseExistingCluster` comment
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1441 🌱 Adding certwatcher as an external package
  pkg/certwatcher/certwatcher.go
  pkg/certwatcher/certwatcher_suite_test.go
  pkg/certwatcher/certwatcher_test.go
  pkg/certwatcher/doc.go
  pkg/certwatcher/example_test.go
  pkg/certwatcher/testdata/.gitkeep
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1451 :bug: Event recorder should not send events when broadcaster is stopped
  pkg/internal/recorder/recorder.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1450 📖 Update godoc links
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS, tide/merge-method-squash
