Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-07, with the labels that each got.

#1573 🌱 cleanup Use objectutil IsAPINamespaced
  pkg/client/namespaced_client.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1582 :warning: Fakeclient: Reject Delete with mismatched ResourceVersion
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1587 :warning: Disable the `rest_client_request_latency_seconds` metric by default
  pkg/metrics/client_go_adapter.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1584 📖 tmp-logging - fix markdown parsing error
  TMP-LOGGING.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1466 📖 Remove extraneous "s" in pkg/events in GoDoc
  doc.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, ok-to-test, size/XS, tide/merge-method-squash

#1596 📖 Add godoc badge to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1597 :book: Update doc.go
  pkg/builder/doc.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1588 ✨ add health check for webhook server
  pkg/webhook/server.go
  pkg/webhook/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1598 ✨ make it possible to monitor if the webhook server has been started
  pkg/webhook/server.go
  pkg/webhook/server_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1602 ✨Restrict namespace for list/watch based on field selectors
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1604 ✨ Update Kubernetes dependencies to v0.21.3
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1605 🐛 Use non blocking file locking for flock library
  pkg/internal/flock/errors.go
  pkg/internal/flock/flock_unix.go
  pkg/internal/testing/addr/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1614 :running: Add varshaprasad96 as reviewer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1615 🐛 fix the typo of certwatcher example test
  pkg/certwatcher/example_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1617 🐛 fix webhook health check tls handshake timeout errors
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1616 🐛 0.9: fix webhook health check tls handshake timeout errors
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S
