Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-12, with the labels that each got.

#1710 :sparkles: Allow configuring a default cache selector
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/internal/informers_map.go
  pkg/cache/internal/selector.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1736 :seedling: Bump golang.org/x/text to v0.3.7
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1738 ⚠️ Update k8s.io/* dependencies to v0.23.0-rc.1
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1741 ✨ Upgrade to Kubernetes v1.23
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1722 📖 Fix a small typo
  pkg/internal/testing/process/process.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1743 :bug: Correctly pass cache options on
  pkg/cache/cache.go
  pkg/cache/internal/informers_map.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#1753 🌱 Add FillZpp as a reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm
