Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-05, with the labels that each got.

#1502 🐛 fix nil Decoder in multiValidating and multiMutating handlers by implementing DecoderInjector
  pkg/manager/internal.go
  pkg/webhook/admission/multi.go
  pkg/webhook/webhook_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#1503 :bug: Run unittests in CI
  Makefile
  hack/test-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1479 ✨ Cache-Backed Client: Support `listOpts.Limit`
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/multi_namespace_cache.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M, tide/merge-method-squash

#1512 :bug: Webhook servers should always start before cache syncs
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1510 :bug: Fakeclient: Support WithWatch
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1513 :bug: Quote path with -p env in envtest-setup
  tools/setup-envtest/env/env.go
  tools/setup-envtest/env/env_suite_test.go
  tools/setup-envtest/env/env_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1521 :bug: Fakeclient: Fix List for unregistered type through unstructured
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1523 :bug: honor LeaderElectionReleaseOnCancel
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1440 🌱 adding TokenReview.auth.k8s.io/v1 webhook support
  examples/tokenreview/main.go
  examples/tokenreview/tokenreview.go
  pkg/webhook/admission/http.go
  pkg/webhook/authentication/authentication_suite_test.go
  pkg/webhook/authentication/doc.go
  pkg/webhook/authentication/http.go
  pkg/webhook/authentication/http_test.go
  pkg/webhook/authentication/response.go
  pkg/webhook/authentication/response_test.go
  pkg/webhook/authentication/webhook.go
  pkg/webhook/authentication/webhook_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1525 ⚠️ Envtest should modify CRDs appropriately when using webhooks
  pkg/envtest/crd.go
  pkg/envtest/server.go
  pkg/envtest/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1526 :seedling: Handle unstructured CRD objects in envtest webhook mods
  pkg/envtest/crd.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1531 🐛 Envtest conversion mods should set strategy and review versions
  pkg/envtest/crd.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1532 :bug: Envtest should enable conversion only for convertible GVKs
  pkg/envtest/crd.go
  pkg/envtest/server.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1533 🌱 Use gomodules.xyz/jsonpatch/v2 v2.2.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1515 :seedling: Fix a typo
  examples/scratch-env/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1504 ✨ Cleanup Webhook server setup
  pkg/envtest/envtest_test.go
  pkg/envtest/server.go
  pkg/envtest/webhook.go
  pkg/envtest/webhook_test.go
  pkg/webhook/server_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1520 :bug: filter global namespace while looking for cluster scoped resources
  pkg/cache/multi_namespace_cache.go
  pkg/internal/objectutil/objectutil.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M, tide/merge-method-squash

#1540 :sparkles: Clean up pkg/internal/testing
  hack/check-everything.sh
  pkg/builder/builder_suite_test.go
  pkg/envtest/server.go
  pkg/envtest/webhook.go
  pkg/internal/testing/addr/addr_suite_test.go
  pkg/internal/testing/addr/manager.go
  pkg/internal/testing/addr/manager_test.go
  pkg/internal/testing/certs/tinyca.go
  pkg/internal/testing/controlplane/apiserver.go
  pkg/internal/testing/controlplane/controlplane_suite_test.go
  pkg/internal/testing/controlplane/etcd.go
  pkg/internal/testing/controlplane/kubectl.go
  pkg/internal/testing/controlplane/kubectl_test.go
  pkg/internal/testing/controlplane/plane.go
  pkg/internal/testing/integration/.gitignore
  pkg/internal/testing/integration/README.md
  pkg/internal/testing/integration/assets/bin/.gitkeep
  pkg/internal/testing/integration/doc.go
  pkg/internal/testing/integration/integration_suite_test.go
  pkg/internal/testing/integration/internal/apiserver.go
  pkg/internal/testing/integration/internal/apiserver_test.go
  pkg/internal/testing/integration/internal/arguments_test.go
  pkg/internal/testing/integration/internal/etcd.go
  pkg/internal/testing/integration/internal/etcd_test.go
  pkg/internal/testing/integration/internal/integration_tests/apiserver_integration_test.go
  pkg/internal/testing/integration/internal/integration_tests/doc.go
  pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
  pkg/internal/testing/integration/internal/integration_tests/integration_test.go
  pkg/internal/testing/integration/internal/process.go
  pkg/internal/testing/integration/internal/process_test.go
  pkg/internal/testing/process/arguments.go
  pkg/internal/testing/process/bin_path_finder.go
  pkg/internal/testing/process/bin_path_finder_test.go
  pkg/internal/testing/process/process.go
  pkg/internal/testing/process/process_suite_test.go
  pkg/internal/testing/process/process_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1541 ✨ Structured args in Testing
  pkg/internal/testing/controlplane/apiserver.go
  pkg/internal/testing/controlplane/etcd.go
  pkg/internal/testing/process/arguments.go
  pkg/internal/testing/process/arguments_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XL
