Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-02, with the labels that each got.

#1371 :warning: Support global controller options in component config
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/config/v1alpha1/types.go
  pkg/config/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1372 :warning: deps: k8s v1.21
  go.mod
  go.sum
  pkg/client/options_test.go
  pkg/scheme/scheme_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1379 🐛 Fix a race condition between leader election and recorder
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1381 🐛 [relase-0.8] Fix a race condition between leader election and recorder
  pkg/manager/internal.go
  pkg/manager/manager.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1382 :sparkles: revert injection deprecation logging until internal injection code use stops
  pkg/cluster/cluster.go
  pkg/internal/controller/controller.go
  pkg/manager/internal.go
  pkg/runtime/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1331 🐛: internal: fix a possible temporary directory leak
  pkg/internal/testing/integration/internal/process.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1341 🌱: testing: Cleanup temporary files
  pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
  pkg/webhook/server_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1389 ⚠ Update Kubernetes 1.21 deps + Go 1.16
  go.mod
  go.sum
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#1391 :seedling: Fix typo namespace/Name to Namespace/Name
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1373 :sparkles: Add tests in controller that use source.Channel
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1394 :bug: Run verify workflow after pushes
  .github/workflows/verify.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1398 📖 Typo: fix typo in validatingwebhook example
  examples/builtins/validatingwebhook.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS
