Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-04, with the labels that each got.

#1467 :bug: Fakeclient: Do not require ListKind
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1470 📖 Fix doc strings for Complete() and Build().
  pkg/builder/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1472 🌱 Update dependencies to v0.21.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#1460 :sparkles: Add ClientWithWatch for use in CLIs
  pkg/client/client.go
  pkg/client/interfaces.go
  pkg/client/watch.go
  pkg/client/watch_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1419 :seedling: Add a design document to filter cache by selectors
  designs/use-selectors-at-cache.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1468 ✨ Surface API Server warnings in client
  pkg/client/client.go
  pkg/log/warning_handler.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L, tide/merge-method-squash

#1483 🌱 Add darwin arch condition for envtest script
  hack/setup-envtest.sh
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#1485 :sparkles: pkg/log/zap: clarify zap level vs. logr verbosity
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/M

#1429 ✨ Simple helper for unmanaged webhook server
  pkg/webhook/admission/webhook.go
  pkg/webhook/example_test.go
  pkg/webhook/internal/metrics/metrics.go
  pkg/webhook/server.go
  pkg/webhook/server_test.go
  pkg/webhook/webhook_integration_test.go
  pkg/webhook/webhook_suite_test.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#1490 🐛 Actually inject the scheme in StandaloneWebhook
  pkg/webhook/admission/admissiontest/doc.go
  pkg/webhook/admission/admissiontest/util.go
  pkg/webhook/admission/validator_test.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/webhook_integration_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1435 :sparkles: Add SelectorsByObject option to cache
  Makefile
  hack/test-all.sh
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/internal/deleg_map.go
  pkg/cache/internal/informers_map.go
  pkg/cache/internal/selector.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#1484 :bug: Metadata only objects should always preserve GroupVersionKind
  pkg/builder/controller_test.go
  pkg/cache/cache_test.go
  pkg/cache/internal/informers_map.go
  pkg/cache/internal/metadata_infomer_wrapper.go
  pkg/client/apiutil/apimachinery.go
  pkg/client/client.go
  pkg/client/client_cache.go
  pkg/client/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1403 🐛 controllerutil.CreateOrPatch doesn't update not empty Status fields if Spec fields are specified
  pkg/controller/controllerutil/controllerutil.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1501 📖 Better document TLS requirements for webhook servers
  pkg/webhook/admission/webhook.go
  pkg/webhook/example_test.go
  pkg/webhook/server.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1500 :bug: add manager.Options.WebhookServer so webhook server can be set
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#1418 🐛 Modify multinamespaced cache to support cluster scoped resources
  pkg/cache/cache_test.go
  pkg/cache/multi_namespace_cache.go
  pkg/client/namespaced_client.go
  pkg/internal/objectutil/objectutil.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#1488 :sparkles: EnvTest Binaries Setup Tool
  Makefile
  hack/check-everything.sh
  hack/setup-envtest.sh
  tools/setup-envtest/README.md
  tools/setup-envtest/env/env.go
  tools/setup-envtest/env/exit.go
  tools/setup-envtest/env/helpers.go
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
  tools/setup-envtest/main.go
  tools/setup-envtest/remote/client.go
  tools/setup-envtest/store/helpers.go
  tools/setup-envtest/store/store.go
  tools/setup-envtest/store/store_suite_test.go
  tools/setup-envtest/store/store_test.go
  tools/setup-envtest/versions/misc_test.go
  tools/setup-envtest/versions/parse.go
  tools/setup-envtest/versions/parse_test.go
  tools/setup-envtest/versions/platform.go
  tools/setup-envtest/versions/selectors_test.go
  tools/setup-envtest/versions/version.go
  tools/setup-envtest/versions/versions_suite_test.go
  tools/setup-envtest/workflows/workflows.go
  tools/setup-envtest/workflows/workflows_suite_test.go
  tools/setup-envtest/workflows/workflows_test.go
  tools/setup-envtest/workflows/workflows_testutils_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL
