Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-01, with the labels that each got.

#1313 ✨ Use anonymous function for locking when serving health probes
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1312 ✨ Fix some typos
  pkg/cache/internal/informers_map.go
  pkg/client/codec.go
Labels: approved, cncf-cla: yes, lgtm, size/XS, tide/merge-method-squash

#1306 ⚠ Fakeclient: Set ResourceVersion when adding objects to the tracker
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1309 🐛 pkg/log: Set Log to NullLogger after 30 seconds
  pkg/log/log.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1307 ✨ Move cluster-specifics from Manager into new pkg/cluster
  pkg/cluster/client_builder.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_suite_test.go
  pkg/cluster/cluster_test.go
  pkg/cluster/internal.go
  pkg/manager/client_builder.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1320 📖: Fix IntoContext() documentation
  pkg/log/log.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1247 :sparkles: Allow configuring cache sync timeouts
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#1324 ✨ initialize reconciler metrics when controller is started
  pkg/internal/controller/controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1315 ✨ introduce LabelChangedPredicate to trigger event on label change
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L, tide/merge-method-squash

#1329 :seedling: Backport bug fixes for v0.7.1 release
  pkg/log/log.go
  pkg/webhook/admission/response.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1326 🐛 ignore namespace key when getting cluster-scoped resources
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/internal/informers_map.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1322 :sparkles: Deprecate Inject interface
  pkg/runtime/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1334 ✨ Adding WithContextFunc for webhook server to pass info to the handler
  pkg/webhook/admission/http.go
  pkg/webhook/admission/http_test.go
  pkg/webhook/admission/webhook.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1336 ✨ Checking configfile examples on check_everything.sh
  hack/check-everything.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1332 🐛 pkg/client: optionally allow caching of unstructured objects
  pkg/client/client_test.go
  pkg/client/split.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1335 :sparkles: Bump k8s dependencies to 1.20.2
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1339 :bug: Fix a race in the delegating logger
  pkg/log/deleg.go
  pkg/log/log_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#1345 :bug: Prevent source.Channel from shutting down immediately
  pkg/internal/controller/controller.go
  pkg/source/source.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/M

#1351 🐛 pkg/client: optionally allow caching of unstructured objects
  pkg/client/client_test.go
  pkg/client/split.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1327 ✨ Manager: Start all caches before other Runnables
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1354 :bug: Manager.Elected() should beclosed after runnables are started
  pkg/manager/internal.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1355 ✨Fix context.TODO() in the example
  examples/builtins/controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#1340 🌱 fix DestWritter var name typo
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#1348 :sparkles: Allow panic as an option to -zap-stacktrace-level"
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#1361 :warning: Fix some more races in the delegating logger
  pkg/log/deleg.go
  pkg/log/log_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#1362 :bug: Don't hotloop on channel source closure
  pkg/source/source.go
  pkg/source/source_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M
