Repository kubernetes-sigs/controller-runtime, pull requests merged in 2021-09, with the labels that each got.

#1650 🐛 set partialmetadata gvk in list/watch funcs to avoid data race in cache
  pkg/builder/controller_test.go
  pkg/cache/internal/informers_map.go
  pkg/cache/internal/metadata_infomer_wrapper.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1651 🐛 Fix object overwrite on patch for fake client
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#1664 :bug: Unconditionally set NegotiatedSerializer
  pkg/client/apiutil/apimachinery.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1662 :bug: Fakeclient: Allow manipulating registered types through unstructured
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#1665 🐛 envtest: get gvk from hook struct instead of forcing set TypeMeta
  pkg/envtest/webhook.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1666 🐛 envtest: fix CRD installation
  pkg/envtest/crd.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1671 🏃 Update k8s.io/* dependencies to 0.22.2
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1674 ✨Switch from rsa to ecdsa in tinyca
  pkg/internal/testing/certs/tinyca.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1677 🐛 client/config: use filepath.Join for loadingRules.Precedence
  pkg/client/config/config.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1676 :sparkles: Allow webhooks to register custom validators/defaulter types
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
  pkg/webhook/admission/defaulter_custom.go
  pkg/webhook/admission/validator_custom.go
  pkg/webhook/alias.go
Labels: cncf-cla: yes, size/L, approved, lgtm
