Repository kubernetes-sigs/controller-runtime, pull requests merged in 2022-11, with the labels that each got.

#2031 :sparkles: feat: add NOT predicate
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2039 🐛 fix: improve semantics of combining cache selectorsByObject
  pkg/cache/cache.go
  pkg/cache/cache_unit_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2043 ⚠ Bump K8s v0.26.0-alpha.3
  go.mod
  go.sum
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/controller/controllertest/util.go
  pkg/envtest/crd.go
  pkg/envtest/webhook.go
  pkg/healthz/healthz.go
  pkg/source/source_integration_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2046 ⚠ Support registration and removal of event handler
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/multi_namespace_cache.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2049 🐛 Skip custom mutation handler when delete a CR
  pkg/webhook/admission/defaulter_custom.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2050 :seedling: Add Dependabot for dependency management
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2056 :sparkles: Add function to get reconcileID from context
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: cncf-cla: yes, size/M, approved, needs-ok-to-test, lgtm

#2057 :sparkles: Tidy up startup logging of kindWithCache source
  pkg/source/source.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2065 :seedling: seedling to dependabot
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2071 :seedling: Ignore Kubernetes Dependencies in Dependabot
  .github/dependabot.yml
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2054 :sparkles: Add cluster.NewClientFunc with options
  pkg/cluster/cluster.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2051 :bug: Missing error log for in-cluster config
  pkg/client/config/config.go
Labels: cncf-cla: yes, approved, size/S, needs-ok-to-test, lgtm

#2072 :warning: Add client.SubResourceWriter
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/dryrun_test.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/metadata_client.go
  pkg/client/namespaced_client.go
  pkg/client/namespaced_client_test.go
  pkg/client/options.go
  pkg/client/split.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
  pkg/envtest/komega/default.go
  pkg/envtest/komega/interfaces.go
  pkg/envtest/komega/komega.go
Labels: cncf-cla: yes, size/XL, approved, lgtm
