Repository kubernetes-sigs/controller-runtime, pull requests merged in 2022-06, with the labels that each got.

#1917 ⚠ Add GetOptions as optional argument of client.Reader and all its implementation
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/multi_namespace_cache.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/fake/client.go
  pkg/client/interfaces.go
  pkg/client/metadata_client.go
  pkg/client/namespaced_client.go
  pkg/client/options.go
  pkg/client/options_test.go
  pkg/client/split.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
  pkg/controller/controllerutil/controllerutil_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1926 📖 fix typo and format this file
  designs/use-selectors-at-cache.md
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#1924 :sparkles: fix some typos
  pkg/client/client.go
  pkg/client/namespaced_client.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1930 🐛 Fix webhook write response error for broken HTTP connection
  pkg/webhook/admission/http.go
  pkg/webhook/admission/http_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#1833 ✨ komega: add EqualObject matcher
  go.mod
  pkg/envtest/komega/equalobject.go
  pkg/envtest/komega/equalobject_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#1935 ✨ Bump k8s.io packages to v1.24.2
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#1937 ✨ Bump dependencies
  go.mod
  go.sum
  pkg/client/patch.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#1939 📖 nit: fix in client package documentation
  pkg/client/doc.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1944 ⚠️ Do not mutate the global warning handler
  pkg/client/client.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test
