Repository kubernetes-sigs/controller-runtime, pull requests merged in 2022-03, with the labels that each got.

#1818 ✨ manager.go: Fix a few Options fields' go-docs
  pkg/manager/manager.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#1767 ✨ Add Kubernetes Gomega extension with to make testing controllers easier
  go.mod
  go.sum
  pkg/envtest/komega/OWNERS
  pkg/envtest/komega/default.go
  pkg/envtest/komega/default_test.go
  pkg/envtest/komega/interfaces.go
  pkg/envtest/komega/komega.go
  pkg/envtest/komega/komega_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#1827 ⚠ logging: align to Kubernetes structured logging, add reconcileID
  go.mod
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#1837 :book: Add documentation for zap-time-encoding flag
  pkg/log/zap/zap.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#1843 ✨Upgrade k8s dependencies from 1.23.0 to 1.23.5
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#1853 ✨Upgrade k8s dependencies from 1.23.0 to 1.23.5
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash

#1846 ✨ [WIP] Add BaseContext to manager Options for use with Runnables
  pkg/manager/manager.go
  pkg/manager/runnable_group.go
  pkg/manager/runnable_group_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test
