Repository kubernetes-sigs/controller-runtime, pull requests merged in 2022-02, with the labels that each got.

#1781 🐛 Inject func in `predicate.{And,Or}`
  pkg/predicate/predicate.go
  pkg/predicate/predicate_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#1790 :bug: Fixed a bug in newGVKFixupWatcher which caused the metadata informer to hang
  pkg/cache/internal/informers_map.go
  pkg/cache/internal/informers_map_test.go
  pkg/cache/internal/internal_suite_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#1797 :book: docs Update design readme
  designs/README.md
Labels: cncf-cla: yes, approved, size/S, needs-ok-to-test, lgtm

#1803 :bug: Use leader config for election events
  pkg/manager/manager.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#1806 🌱 Add controller-name as kv pair to logger instead of as name
  pkg/controller/controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1808 :bug: Cache sync cancelled should not error with timeout
  pkg/internal/controller/controller_test.go
  pkg/source/source.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1813 🐛 prometheus/client_golang 0.11.0 -> 0.11.1 - fix DoS
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#1747 📖 Explain what may happen when using OnlyMetadata and Get on the concrete type instead of PartialMetadataObject
  pkg/builder/options.go
Labels: cncf-cla: yes, approved, size/S, needs-ok-to-test, lgtm, tide/merge-method-squash

#1807 🐛 Check to see if obj is nil so there is no panic trying to get the gvk
  pkg/log/zap/kube_helpers.go
  pkg/log/zap/zap_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, tide/merge-method-squash, ok-to-test

#1810 🌱 log panic in reconcile even if panic should not be recovered
  pkg/internal/controller/controller.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#1815 :book: Fix examples typo
  pkg/client/example_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
