Repository kubernetes-sigs/controller-runtime, pull requests merged in 2022-09, with the labels that each got.

#1992 📖 add comments for configuration
  pkg/config/v1alpha1/types.go
  pkg/manager/manager.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1970 🐛 Conversion webhook should not panic when conversion request is nil
  pkg/webhook/conversion/conversion.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#1795 🌱 Refactor typed_client and unstructured_client to be consistent
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#2006 🌱 grammar: removed doubles of the word "the"
  TMP-LOGGING.md
  pkg/builder/options.go
  pkg/log/zap/zap.go
  tools/setup-envtest/README.md
  tools/setup-envtest/main.go
  tools/setup-envtest/workflows/workflows.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2012 🌱 Bump kubebuilder-release-tools to v0.2.0
  .github/workflows/verify.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2013 🌱 Add sbueringer as reviewer
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm
