Repository kubernetes-sigs/controller-runtime, pull requests merged in 2023-04, with the labels that each got.

#2272 🐛 Use Go 1.19 in golangci-lint action
  .github/workflows/golangci-lint.yml
  Makefile
Labels: cncf-cla: yes, approved, size/XS, lgtm

#1943 ✨ Introduce pprof server to manager
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/server.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#2259 :warning: Fakeclient: Fix status handling
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2279 ✨ Update Go to 1.20
  .github/workflows/golangci-lint.yml
  .golangci.yml
  go.mod
  pkg/cache/internal/informers.go
  tools/setup-envtest/store/store_test.go
  tools/setup-envtest/workflows/workflows_testutils_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2282 🌱 Add client.InNamespace("xyz").AsSelector()
  pkg/client/options.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2014 :warning: feat: new features about support warning with webhook
  examples/builtins/validatingwebhook.go
  examples/crd/pkg/resource.go
  pkg/builder/webhook_test.go
  pkg/webhook/admission/admissiontest/doc.go
  pkg/webhook/admission/admissiontest/util.go
  pkg/webhook/admission/validator.go
  pkg/webhook/admission/validator_custom.go
  pkg/webhook/admission/validator_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, ok-to-test

#2284 :seedling: Update golangci-lint to v1.52.1
  .github/workflows/golangci-lint.yml
  .golangci.yml
  pkg/predicate/predicate_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2289 :seedling: envtest: set default webhook options for polling
  pkg/envtest/webhook.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2286 🐛 Fix race condition in channel source
  pkg/source/source.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, tide/merge-method-squash, ok-to-test

#2290 🌱 Kind source should expose type information on timeout
  pkg/internal/source/kind.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
