Repository kubernetes-sigs/controller-runtime, pull requests merged in 2023-06, with the labels that each got.

#2367 :bug: SetLogger should work with nil sinks
  pkg/log/deleg.go
  pkg/log/log_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2365 🐛 fakeClient.Status().Update(...) cannot recognize resource version conflicts
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2363 🐛 hasLabels and matchingLabels step on each other
  pkg/client/options.go
  pkg/client/options_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#2261 :book: Add a design for cache options configuration
  designs/cache_options.md
Labels: cncf-cla: yes, size/L, approved, lgtm

#2392 ✨ fake: Update fake client doc.go to avoid the deprecated method
  pkg/client/fake/doc.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, tide/merge-method-squash, ok-to-test
