Repository kubernetes-sigs/controller-runtime, pull requests merged in 2023-02, with the labels that each got.

#2163 :running: Use HTTPClient to create the API Reader
  pkg/cluster/cluster.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2164 🌱Return an error if no httpClient is provided
  pkg/client/apiutil/apimachinery.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2165 🌱 [0.14] Deprecate component configuration package
  alias.go
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/doc.go
  pkg/config/example_test.go
  pkg/config/v1alpha1/doc.go
  pkg/config/v1alpha1/register.go
  pkg/config/v1alpha1/types.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/manager/example_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_options_test.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2166 ⚠ Cache's ByObject is now a map Object -> options
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/cache_unit_test.go
  pkg/cache/internal/disabledeepcopy.go
  pkg/cache/internal/informers.go
  pkg/cache/internal/selector.go
  pkg/cache/multi_namespace_cache.go
  pkg/cluster/cluster.go
  pkg/manager/example_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#2170 :book: Fix typo in ComponentConfig Godoc
  pkg/config/v1alpha1/types.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2168 🌱 Use runtime.Unstructured interface instead of Unstructured struct
  pkg/cache/informer_cache.go
  pkg/cache/internal/informers.go
  pkg/client/client.go
  pkg/client/client_rest_resources.go
  pkg/client/fake/client.go
  pkg/client/unstructured_client.go
  pkg/client/watch.go
  pkg/envtest/komega/equalobject.go
  pkg/webhook/admission/decode.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2162 📖 Add inteon to reviewers
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2178 🌱Return an error if no httpClient is provided for `NewDynamicRESTMapper`
  pkg/client/apiutil/dynamicrestmapper.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2116 ✨ Provide a truly lazy restmapper
  pkg/client/apiutil/dynamicrestmapper.go
  pkg/client/apiutil/lazyrestmapper.go
  pkg/client/apiutil/lazyrestmapper_test.go
  pkg/client/apiutil/testdata/crd.yaml
Labels: cncf-cla: yes, size/XL, approved, lgtm

#2177 ✨ Expose Cache/Client options on Cluster
  pkg/client/client.go
  pkg/client/client_suite_test.go
  pkg/client/client_test.go
  pkg/client/dryrun_test.go
  pkg/cluster/cluster.go
  pkg/manager/manager.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2180 :seedling: code clean for pkg/envtest/server.go
  pkg/envtest/server.go
Labels: cncf-cla: yes, approved, size/S, lgtm, kind/cleanup, ok-to-test

#2188 🌱 Bump golangci-lint to v1.51.1
  .github/workflows/golangci-lint.yml
  .golangci.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2186 🌱 verify.sh: verify generate & modules (in CI)
  Makefile
  hack/verify.sh
Labels: cncf-cla: yes, size/M, approved, lgtm

#2187 🌱 Bump controller-tools to v0.11.3 and apidiff to v0.5.0
  hack/tools/go.mod
  hack/tools/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#2169 🐛 Allow to set GracefulShutdownTimeout to -1, disabling timeouts
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2201 📖 Fix a typo in a godoc comment
  pkg/client/fake/client.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2192 🌱 GVKForObject should handle multiple GVKs in Scheme gracefully
  pkg/client/apiutil/apimachinery.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2203 📖 Replace occurences of master with main
  .github/workflows/golangci-lint.yml
  README.md
  RELEASE.md
  doc.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2200 🌱 Provide more information on deprecating ComponentConfig
  pkg/manager/manager.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2199 ⚠ Expose Manager.Cache/Client options, deprecate older opts
  .golangci.yml
  pkg/cache/cache.go
  pkg/cache/cache_unit_test.go
  pkg/cluster/cluster.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm
