Repository kubernetes-sigs/controller-runtime, pull requests merged in 2023-03, with the labels that each got.

#2208 🐛 Allow lazy restmapper to work with CRDs created at runtime
  pkg/client/apiutil/lazyrestmapper.go
  pkg/client/apiutil/lazyrestmapper_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2219 [release-0.14] 🐛 Allow lazy restmapper to work with CRDs created at runtime
  pkg/client/apiutil/lazyrestmapper.go
  pkg/client/apiutil/lazyrestmapper_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2223 🐛 Add cross-version compatibility with client-go 1.27
  pkg/cache/multi_namespace_cache.go
  pkg/controller/controllertest/util.go
  pkg/internal/source/event_handler.go
  pkg/internal/source/kind.go
  pkg/source/source.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2234 🌱 Don't call defaultOpts for MultiNamespaceCache twice
  pkg/cache/cache.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2246 🐛 Preserve unstructured object GVKs in cache.Options.ByObject
  pkg/cache/cache.go
  pkg/cache/cache_unit_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2252 :bug: fix a bug in multinamespaced cache implementation
  pkg/cache/multi_namespace_cache.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2257 🐛 ForceOwnership should work with subresources
  pkg/client/options.go
  pkg/client/options_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm
