Repository kubernetes-sigs/controller-runtime, pull requests merged in 2023-05, with the labels that each got.

#2291 🌱 Handle TLSOpts.GetCertificate in webhook
  pkg/webhook/server.go
  pkg/webhook/server_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2189 :sparkles: upgrade to k8s 0.27.1
  go.mod
  go.sum
  pkg/certwatcher/certwatcher.go
  pkg/envtest/crd.go
  pkg/envtest/webhook.go
  pkg/internal/source/kind.go
  pkg/log/zap/kube_helpers.go
  pkg/log/zap/zap_test.go
  pkg/manager/internal.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#2296 :warning: Use and provide a single dynamic rest mapper
  go.mod
  hack/tools/go.mod
  hack/tools/go.sum
  pkg/cache/informer_cache_test.go
  pkg/client/apiutil/dynamicrestmapper.go
  pkg/client/apiutil/dynamicrestmapper_test.go
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_test.go
  pkg/cluster/cluster.go
  pkg/webhook/webhook_integration_test.go
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2293 ⚠️ Allow passing a custom webhook server
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
  pkg/manager/internal.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/runnable_group.go
  pkg/manager/runnable_group_test.go
  pkg/webhook/example_test.go
  pkg/webhook/server.go
  pkg/webhook/server_test.go
  pkg/webhook/webhook_integration_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2303 🐛 Client: use passed in Cache.DisableFor option
  pkg/client/client.go
  pkg/client/client_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2300 :warning: Remove cache.BuilderWithOptions, and inheritance funcs
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/cache_unit_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#2301 🌱 Add certwatcher callback
  pkg/certwatcher/certwatcher.go
  pkg/certwatcher/certwatcher_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2275 🌱 Make metrics and health probe servers be Runnables
  pkg/manager/internal.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2305 :sparkles: Fakeclient: Add support for evictions
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2307 ⚠️ Flatten fields in controller.Options
  pkg/builder/controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2317 :warning: Unexport delegating logger, remove async init
  pkg/log/deleg.go
  pkg/log/log.go
  pkg/log/log_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2319 :seedling: update builtin webhook paths
  examples/builtins/mutatingwebhook.go
  examples/builtins/validatingwebhook.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2318 :seedling: Update SECURITY_CONTACTS and maintainer list
  OWNERS_ALIASES
  SECURITY_CONTACTS
Labels: cncf-cla: yes, approved, size/S, lgtm

#2321 🐛 Revert: move health probes to runnable
  pkg/manager/internal.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2324 📖 Fix typo in client example
  pkg/client/example_test.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2326 ✨ Cleanup webhook logging
  pkg/builder/webhook.go
  pkg/webhook/admission/http.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/admission/webhook_test.go
  pkg/webhook/authentication/http.go
  pkg/webhook/authentication/webhook.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2329 🌱 Fix webhook options deprecation notes
  pkg/manager/manager.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2316 ⚠ Update fake client deletionTimestamp behavior
  go.mod
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#2333 🌱 Re-enable tests for v0.27.2
  pkg/log/zap/zap_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2334 ⚠ Change webhook request received / response written logs to log level 4
  pkg/webhook/admission/http.go
  pkg/webhook/authentication/http.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2338 :seedling: bump jsonpatch to v2.3.0
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2343 ✨Fix logs in unstructured client
  pkg/client/unstructured_client.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2346 🐛 fix unspecified KindsFor version
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test
