Repository kubernetes-sigs/controller-runtime, pull requests merged in 2023-08, with the labels that each got.

#2435 :bug: Fix Defaulting of the User Agent
  pkg/cache/cache.go
  pkg/client/client.go
  pkg/cluster/cluster.go
  pkg/manager/manager.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2412 ⚠ fake client: use correct RBAC apiGroup name when deciding if to allow unconditional updates
  pkg/client/fake/client.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, tide/merge-method-squash, ok-to-test

#2438 :bug: Fix TerminalError(nil).Error() panic
  pkg/reconcile/reconcile.go
  pkg/reconcile/reconcile_test.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2439 :warning: Return an error if the continue list option is set for the cache reader
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2407 ⚠ Introduce Metrics Options struct & secure metrics serving
  examples/scratch-env/go.sum
  go.mod
  go.sum
  pkg/builder/builder_suite_test.go
  pkg/controller/controller_suite_test.go
  pkg/manager/internal.go
  pkg/manager/internal/integration/manager_test.go
  pkg/manager/manager.go
  pkg/manager/manager_suite_test.go
  pkg/manager/manager_test.go
  pkg/metrics/filters/filters.go
  pkg/metrics/listener.go
  pkg/metrics/server/doc.go
  pkg/metrics/server/server.go
  pkg/webhook/conversion/testdata/main.go
  pkg/webhook/server.go
  pkg/webhook/webhook_integration_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2444 :book: Clarify that the reconcile.Result is ignored on non-nil error
  pkg/reconcile/reconcile.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2448 🌱 Fix mail of dependabot action commit
  .github/workflows/pr-dependabot.yaml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2433 🐛 Add missing return statement in the webhook admissions func
  pkg/webhook/admission/decode.go
  pkg/webhook/admission/decode_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#2449 🌱 Bump to k8s.io v1.28.0
  examples/scratch-env/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#2406 ✨: pkg/cache: add options for cache miss policy
  Makefile
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/informer_cache.go
  pkg/cache/internal/informers.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#2451 🌱 log warning if error and non-zero Result returned
  pkg/internal/controller/controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2371 ✨ Allow non-blocking retrieval of informers
  pkg/builder/controller_test.go
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/delegating_by_gvk_cache.go
  pkg/cache/informer_cache.go
  pkg/cache/informertest/fake_cache.go
  pkg/cache/internal/informers.go
  pkg/cache/multi_namespace_cache.go
  pkg/internal/controller/controller_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#2465 [release-0.16] 🐛 Refactor tests to drop hard otel dependency
  examples/scratch-env/go.sum
  pkg/manager/manager_test.go
  pkg/metrics/filters/filter_suite_test.go
  pkg/metrics/filters/filters_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm
