Repository kubernetes-sigs/controller-runtime, pull requests merged in 2024-04, with the labels that each got.

#2747 :bug: Cache: Keep selectors when byObject.Namespaces is defaulted
  pkg/cache/cache.go
  pkg/cache/defaulting_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2724 🐛 prevent leader election when shutting down a non-elected manager
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#2750 🐛 Revert "🌱 Bump github.com/prometheus/client_golang"
  go.mod
  go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2751 🌱 Update golanci-lint to v1.57.2
  .github/workflows/golangci-lint.yml
  .golangci.yml
  pkg/manager/internal.go
  tools/setup-envtest/store/store.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2754 ✨ Bump to k/k v0.30.0-rc.1
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#2757 :bug: Runnable group should check if stopped before enqueueing
  pkg/manager/runnable_group.go
  pkg/manager/runnable_group_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2758 :bug: Prevent race when informers are started more than once
  pkg/cache/cache.go
  pkg/cache/cache_test.go
  pkg/cache/internal/informers.go
  pkg/cache/multi_namespace_cache.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2766 🐛 Fix SubResourceCreateOptions signature in subresource client
  pkg/client/client.go
  pkg/client/client_test.go
Labels: cncf-cla: yes, approved, size/S, needs-ok-to-test, lgtm

#2770 :book: Use `Should` instead of `To` in `komega` samples
  pkg/envtest/komega/default.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2767 ✨ Add controller workqueue option
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2771 ✨ client: Add client-wide fieldManager
  pkg/client/fieldmanager_test.go
  pkg/client/fieldowner.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2773 🌱 fix: typo of CacheReader comment
  pkg/cache/internal/cache_reader.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#2776 🌱 Bump to k/k 1.30 RC2, downgrade prometheus, zap, golang.org/x/sys, sigs.k8s.io/yaml
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#2777 🌱 style: rename fieldmanager to fieldowner
  pkg/client/fieldowner.go
  pkg/client/fieldowner_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2725 🐛 allow fakeclient to patch CR with no RV
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#2648 ⚠️ Remove deprecated manager options
  Makefile
  alias.go
  examples/configfile/builtin/config.yaml
  examples/configfile/builtin/controller.go
  examples/configfile/builtin/main.go
  examples/configfile/custom/config.yaml
  examples/configfile/custom/controller.go
  examples/configfile/custom/main.go
  examples/configfile/custom/v1alpha1/types.go
  examples/configfile/custom/v1alpha1/zz_generated.deepcopy.go
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  hack/check-everything.sh
  hack/verify.sh
  pkg/config/config.go
  pkg/config/config_suite_test.go
  pkg/config/config_test.go
  pkg/config/doc.go
  pkg/config/example_test.go
  pkg/config/testdata/config.yaml
  pkg/config/v1alpha1/doc.go
  pkg/config/v1alpha1/register.go
  pkg/config/v1alpha1/types.go
  pkg/config/v1alpha1/zz_generated.deepcopy.go
  pkg/manager/example_test.go
  pkg/manager/manager.go
  pkg/manager/manager_options_test.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm, kind/cleanup, tide/merge-method-squash

#2786 ✨ Bump to k8s.io/* v1.30
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#2473 ✨ Export HTTP server manager runnable implementation
  pkg/manager/internal.go
  pkg/manager/runnable_group.go
  pkg/manager/runnable_group_test.go
  pkg/manager/server.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2789 📖 manager: fix godoc about http servers
  pkg/manager/internal.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2783 ⚠️ Source, Event, Predicate, Handler: Add generics support
  examples/builtins/main.go
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_test.go
  pkg/controller/example_test.go
  pkg/event/event.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/example_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/internal/source/event_handler.go
  pkg/internal/source/internal_test.go
  pkg/internal/source/kind.go
  pkg/predicate/predicate.go
  pkg/source/example_test.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
  pkg/source/source_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2792 🌱 Fix typo in channel option
  pkg/source/source.go
  pkg/source/source_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2796 📖 Mark Typed Handlers as experimental
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2774 🌱 verify go modules are in sync with upstream k/k
  .gomodcheck.yaml
  Makefile
  go.mod
  go.sum
  hack/tools/.keep
  hack/tools/cmd/gomodcheck/main.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test
