Repository kubernetes-sigs/controller-runtime, pull requests merged in 2024-08, with the labels that each got.

#2855 ✨ Add scale subresource logic to fake client
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#2876 🐛 Prevent LeaderElector setup error from being swallowed
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#2893 🐛 Recreate watcher if the file unlinked and replaced
  pkg/certwatcher/certwatcher.go
  pkg/certwatcher/certwatcher_suite_test.go
  pkg/certwatcher/certwatcher_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#2745 🐛 Quiet context.Canceled errors during shutdown
  pkg/manager/internal.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/M, lifecycle/stale, approved, lgtm, ok-to-test

#2900 :running: Bump k8s.io/* deps to v1.31-rc0
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#2899 :book: Builder: Improve godocs
  pkg/builder/controller.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2812 ✨ Add missing generic version of ResourceVersionChangedPredicate
  pkg/predicate/predicate.go
Labels: cncf-cla: yes, lifecycle/stale, approved, size/S, lgtm

#2902 :warning: Validate controller names are unique
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/name.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2905 ⚠ Recover panics per default
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
  pkg/config/controller.go
  pkg/controller/controller.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/controller/metrics/metrics.go
  pkg/webhook/admission/metrics/metrics.go
  pkg/webhook/admission/webhook.go
  pkg/webhook/admission/webhook_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#2903 :warning: Remove options.WarningHandler
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/example_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2910 📖 Document compatibility with k8s.io/*, client-go and Go
  README.md
Labels: cncf-cla: yes, approved, size/S, lgtm

#2906 🏃 Bump k8s.io/* deps to v1.31.0-rc.1
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#2908 🌱 Add action to approve actions if ok-to-test is set
  .github/workflows/pr-gh-workflow-approve.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2913 🐛 Fix WithFieldValidation client
  pkg/client/fieldvalidation_test.go
  pkg/client/options.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2911 ✨ Publish setup-envtest binaries on releases
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-dependabot.yaml
  .github/workflows/release.yaml
  .gitignore
  Makefile
Labels: cncf-cla: yes, size/L, approved, lgtm

#2918 🌱 Add SkipNameValidation option
  pkg/config/controller.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#2924 🌱 Bump k8s.io deps to v1.31.0
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#2915 🌱 setup-envtest: drop support for GCS
  tools/setup-envtest/README.md
  tools/setup-envtest/env/env.go
  tools/setup-envtest/main.go
  tools/setup-envtest/remote/gcs_client.go
  tools/setup-envtest/store/store.go
  tools/setup-envtest/store/store_test.go
  tools/setup-envtest/versions/misc_test.go
  tools/setup-envtest/versions/parse.go
  tools/setup-envtest/versions/platform.go
  tools/setup-envtest/versions/version.go
  tools/setup-envtest/workflows/workflows_test.go
  tools/setup-envtest/workflows/workflows_testutils_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm
