Repository kubernetes-sigs/controller-runtime, pull requests merged in 2024-10, with the labels that each got.

#2969 ✨ fakeclient: Add support for ServiceAccount Token subresource
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#2970 🌱 Remove deprecated cluster.Options.SyncPeriod
  pkg/cluster/cluster.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2950 :bug: upgrade golangci-lint to v1.61.0
  .github/workflows/golangci-lint.yml
  .golangci.yml
  pkg/cache/cache_test.go
  pkg/client/client_test.go
  pkg/envtest/crd.go
  pkg/envtest/envtest_test.go
  pkg/envtest/webhook.go
  pkg/log/zap/flags.go
  pkg/webhook/admission/response.go
  tools/setup-envtest/store/store.go
Labels: cncf-cla: yes, approved, size/S, lgtm, tide/merge-method-squash

#2973 🌱 Fix PR verify action
  .github/workflows/verify.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2971 ✨ Bump to k8s.io/* v0.32.0-alpha.1
  .golangci.yml
  Makefile
  README.md
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  hack/apidiff.sh
  hack/check-everything.sh
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#2985 📖Update docs for setupenvtest
  tools/setup-envtest/README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#2980 :bug: Fakeclient: Fix TOCTOU races
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2990 🌱 Bump to k8s.io/* v0.32.0-alpha.2
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#2993 🐛 Rename SecretSyncReconcier to SecretSyncReconciler (typo)
  examples/multiclustersync/main.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2996 📖 (fix): typo in IndexField method docs
  pkg/client/interfaces.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm
