Repository kubernetes-sigs/controller-runtime, pull requests merged in 2024-02, with the labels that each got.

#2668 :seedling: WaitForDefaultNamespace while starting up envtest
  pkg/envtest/server.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2663 🐛 Clean restmapper cache if a version is notFound
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#2677 [release-0.16] 🐛 Avoid extra calls for not found resource
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2679 :bug: Fakeclient: Do not consider an apply patch to be a strategic merge patch
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2687 🐛 Fix lazy rest mapper cache invalidation
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_wb_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2689 [release-0.16] 🐛 Fix lazy rest mapper cache invalidation
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_wb_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm
