Repository kubernetes-sigs/controller-runtime, pull requests merged in 2024-07, with the labels that each got.

#2867 :running: Bump k8s.io/* deps to v0.31.0-alpha.2
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#2799 :warning: Add TypedReconciler
  .golangci.yml
  examples/multiclustersync/main.go
  examples/typed/main.go
  pkg/builder/controller.go
  pkg/builder/controller_test.go
  pkg/builder/options.go
  pkg/builder/webhook_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/controllertest/testing.go
  pkg/event/event.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
  pkg/handler/example_test.go
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/internal/source/event_handler.go
  pkg/internal/source/internal_test.go
  pkg/internal/source/kind.go
  pkg/predicate/predicate.go
  pkg/ratelimiter/doc.go
  pkg/ratelimiter/ratelimiter.go
  pkg/reconcile/reconcile.go
  pkg/source/source.go
  pkg/source/source_integration_test.go
  pkg/source/source_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#2874 :bug: AddMetricsServerExtraHandler: Info takes key/value pairs
  pkg/manager/internal.go
Labels: cncf-cla: yes, approved, needs-ok-to-test, size/XS, lgtm

#2875 :bug: Fix namespaced GVK check to use version
  pkg/client/apiutil/apimachinery.go
  pkg/client/apiutil/apimachinery_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#2872 :running: Bump k8s.io/* deps to v0.31.0-alpha.3
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  pkg/client/fake/client.go
  pkg/metrics/filters/filters.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#2881 :sparkles: Add dynamic watcher tests
  pkg/controller/controller_integration_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#2883 ✨ Bump to k8s.io/* v0.31.0-beta.0
  .gomodcheck.yaml
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#2887 :bug: Suppress API server warnings in the client
  pkg/client/client.go
  pkg/client/client_suite_test.go
  pkg/client/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#2860 :sparkles: Adds a client that enables strict field validation by default.
  pkg/client/fieldvalidation.go
  pkg/client/fieldvalidation_test.go
  pkg/client/options.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#2895 :sparkles: Workqueue: Add `controller` label
  pkg/metrics/workqueue.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#2894 :book: Improve godocs for source
  pkg/source/source.go
Labels: cncf-cla: yes, approved, size/XS, lgtm
