Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-09, with the labels that each got.

#3304 🌱 Fix typo in unit test name
  pkg/builder/controller_test.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#3306 📖 pkg/client/config: remove outdated doc comments
  pkg/client/config/config.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#3307 🌱 Revert deprecation of client.Apply
  pkg/client/fake/client_test.go
  pkg/client/patch.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3311 :warning: Fakeclient: Set ResourceVersion for SSA Create
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#3319 :warning: Fakeclient: Fix a number of bugs when updating through apply
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/fake/versioned_tracker.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, tide/merge-method-squash
