Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-02, with the labels that each got.

#3095 🌱 Update dependencies, k8s 1.32.1
  Makefile
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#3070 ✨feat: add GoCollector and ProcessCollector metrics
  pkg/internal/controller/metrics/metrics.go
Labels: cncf-cla: yes, approved, size/XS, lgtm, tide/merge-method-squash, ok-to-test

#3103 🐛Fix behavior of rate limit option in priorityqueue.AddWithOpts
  pkg/controller/priorityqueue/priorityqueue.go
  pkg/controller/priorityqueue/priorityqueue_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#3104 ⚠ Bump to k8s.io/* v0.33.0-alpha.1
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  pkg/controller/controllertest/util.go
  pkg/manager/manager_test.go
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#3126 🐛 fix: cache should list out of global cache when present and necessary
  pkg/cache/cache_test.go
  pkg/cache/multi_namespace_cache.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3125 🌱 fix: make test fails with make: *** [Makefile:73: test] Error 1
  hack/apidiff.sh
  hack/check-everything.sh
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test

#3129 🌱 Export envtest.ReadCRDFiles
  pkg/envtest/crd.go
  pkg/envtest/crd_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3119 :warning: Config: Disable client-side ratelimiter by default
  alias.go
  pkg/client/config/config.go
  pkg/client/config/config_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3134 🐛 Return error if pagination is used with the cached client
  pkg/cache/cache_test.go
  pkg/cache/internal/cache_reader.go
  pkg/cache/multi_namespace_cache.go
Labels: cncf-cla: yes, size/M, approved, lgtm
