Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-10, with the labels that each got.

#3329 🌱 [noop] Modernize finalizer utils
  pkg/controller/controllerutil/controllerutil.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#3323 🌱chore: Update golangci-lint version to v2.5.0
  .github/workflows/golangci-lint.yml
  .golangci.yml
  examples/crd/pkg/groupversion_info.go
  examples/tokenreview/tokenreview.go
  pkg/log/zap/flags.go
  pkg/reconcile/reconcile.go
Labels: cncf-cla: yes, approved, size/S, lgtm, tide/merge-method-squash, ok-to-test

#3321 ⚠️ Add subresource apply support
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/dryrun_test.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/fake/versioned_tracker.go
  pkg/client/fieldowner.go
  pkg/client/fieldowner_test.go
  pkg/client/fieldvalidation.go
  pkg/client/fieldvalidation_test.go
  pkg/client/interceptor/intercept.go
  pkg/client/interceptor/intercept_test.go
  pkg/client/interfaces.go
  pkg/client/namespaced_client.go
  pkg/client/namespaced_client_test.go
  pkg/client/options.go
  pkg/client/options_test.go
  pkg/client/patch.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, tide/merge-method-squash

#3333 ✨ Add optional Priority field to reconcile.Result
  pkg/internal/controller/controller.go
  pkg/internal/controller/controller_test.go
  pkg/reconcile/reconcile.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3332 ✨ Priorityqueue: Enable per default
  examples/priorityqueue/main.go
  pkg/config/controller.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm
