Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-07, with the labels that each got.

#3258 📖 Sync admins & maintainers with kubernetes/org
  OWNERS_ALIASES
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3259 :seedling: Bump k8s.io/* deps to v0.34.0-beta.0
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  pkg/client/fake/typeconverter.go
  pkg/client/fake/typeconverter_test.go
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#3253 :warning: Add native SSA support
  pkg/cache/internal/informers.go
  pkg/client/apiutil/apimachinery.go
  pkg/client/applyconfigurations.go
  pkg/client/client.go
  pkg/client/client_rest_resources.go
  pkg/client/client_test.go
  pkg/client/dryrun.go
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/fieldowner.go
  pkg/client/fieldvalidation.go
  pkg/client/fieldvalidation_test.go
  pkg/client/interceptor/intercept.go
  pkg/client/interceptor/intercept_test.go
  pkg/client/interfaces.go
  pkg/client/namespaced_client.go
  pkg/client/namespaced_client_test.go
  pkg/client/options.go
  pkg/client/options_test.go
  pkg/client/patch.go
  pkg/client/typed_client.go
  pkg/client/unstructured_client.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, tide/merge-method-squash

#3247 🐛 Fix(manager): Prevent goroutine leak on shutdown timeout
  pkg/manager/manager.go
  pkg/manager/manager_test.go
  pkg/manager/runnable_group.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#3264 :seedling: Clarify our versioning scheme
  README.md
  VERSIONING.md
Labels: cncf-cla: yes, approved, size/S, lgtm

#3263 :seedling: Stop using context.Background()/TODO() in tests
  .golangci.yml
  pkg/builder/controller_test.go
  pkg/builder/webhook_test.go
  pkg/cache/cache_test.go
  pkg/certwatcher/certwatcher_test.go
  pkg/client/apiutil/apimachinery_test.go
  pkg/client/apiutil/restmapper_test.go
  pkg/client/client_test.go
  pkg/client/dryrun_test.go
  pkg/client/fake/client_test.go
  pkg/client/fieldowner_test.go
  pkg/client/fieldvalidation_test.go
  pkg/client/interceptor/intercept_test.go
  pkg/client/namespaced_client_test.go
  pkg/client/watch_test.go
  pkg/cluster/cluster_test.go
  pkg/controller/controller_integration_test.go
  pkg/controller/controller_test.go
  pkg/controller/controllerutil/controllerutil_test.go
  pkg/envtest/binaries_test.go
  pkg/envtest/envtest_test.go
  pkg/envtest/webhook_test.go
  pkg/finalizer/finalizer_test.go
  pkg/handler/eventhandler_test.go
  pkg/internal/controller/controller_test.go
  pkg/internal/recorder/recorder_integration_test.go
  pkg/internal/source/internal_test.go
  pkg/internal/testing/controlplane/plane_test.go
  pkg/log/log_test.go
  pkg/manager/manager_test.go
  pkg/manager/runnable_group_test.go
  pkg/manager/server.go
  pkg/metrics/filters/filters_test.go
  pkg/reconcile/reconcile_test.go
  pkg/source/source_integration_test.go
  pkg/source/source_suite_test.go
  pkg/source/source_test.go
  pkg/webhook/admission/defaulter_custom_test.go
  pkg/webhook/admission/http_test.go
  pkg/webhook/admission/multi_test.go
  pkg/webhook/admission/validator_custom_test.go
  pkg/webhook/admission/webhook_test.go
  pkg/webhook/authentication/http_test.go
  pkg/webhook/authentication/webhook_test.go
  pkg/webhook/server_test.go
  pkg/webhook/webhook_integration_test.go
  tools/setup-envtest/store/store_suite_test.go
  tools/setup-envtest/store/store_test.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#3266 🌱chore: Update golangci-lint version to v2.3.0
  .github/workflows/golangci-lint.yml
Labels: cncf-cla: yes, approved, size/XS, lgtm, ok-to-test
