Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-03, with the labels that each got.

#3135 ✨ envtest: add option to download binaries, bump envtest to v1.32.0
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  hack/check-everything.sh
  pkg/client/apiutil/restmapper_test.go
  pkg/envtest/binaries.go
  pkg/envtest/binaries_test.go
  pkg/envtest/server.go
Labels: cncf-cla: yes, size/XL, approved, lgtm, tide/merge-method-squash

#3137 🐛 Create BinaryAssetsDirectory if it doesn't exist
  pkg/envtest/binaries.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3141 ⚠️ NewTypedUnmanaged: Stop requiring a manager
  pkg/config/controller.go
  pkg/controller/controller.go
  pkg/controller/example_test.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3142 ✨ Bump to k8s.io/* v0.33.0-alpha.3 and Go 1.24
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  pkg/cache/internal/informers.go
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#3118 📖 chore: Add explanatory comment for continuing to use json-patch v4 in the fake client
  pkg/client/fake/client.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#3143 :bug: Fakeclient: Fix dataraces when writing to the scheme
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3147 [release-0.20] :bug: Revert "✨ Expose all Go runtime metrics"
  pkg/internal/controller/metrics/metrics.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3138 :seedling: Validate that unstructued objects don't require scheme registration
  pkg/client/client_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3150 🐛 Fix race in logger test
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3149 ⚠ Improve logging by adopting contextual logging
  pkg/cache/cache.go
  pkg/cache/internal/informers.go
  pkg/cache/multi_namespace_cache.go
  pkg/controller/controllertest/util.go
  pkg/internal/controller/controller.go
  pkg/internal/source/kind.go
  pkg/log/log_test.go
  pkg/source/source.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#3111 🐛Implement priorityqueue as default on handlers if using priorityqueue interface
  pkg/handler/enqueue.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash

#3152 :seedling: Handlers: Use low priority when object is unchanged and priority queue
  pkg/handler/enqueue_mapped.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3153 :seedling: envtest: fix nil pointer exception in Stop().
  pkg/internal/testing/controlplane/apiserver.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#3151 :bug: Restmapper: Respect preferred version
  pkg/client/apiutil/restmapper.go
  pkg/client/apiutil/restmapper_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#3160 :seedling: Followups to default low priority in mappers
  pkg/handler/enqueue_mapped.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#2828 :bug: fix(controllerutil): avoid panic when the MutateFn is nil
  pkg/controller/controllerutil/controllerutil.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#3161 🌱 Bump to k8s.io/* v0.33.0-beta.0
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#3156 🌱 Add priority label to PQ depth metric
  pkg/controller/priorityqueue/metrics.go
  pkg/controller/priorityqueue/metrics_test.go
  pkg/controller/priorityqueue/priorityqueue.go
  pkg/controller/priorityqueue/priorityqueue_test.go
  pkg/internal/metrics/workqueue.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3162 ✨ Leverage isInInitialList of ResourceEventHandler.OnAdd, Add IsInInitialList to TypedCreateEvent
  pkg/cache/multi_namespace_cache.go
  pkg/controller/controllertest/util.go
  pkg/event/event.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
  pkg/internal/source/event_handler.go
  pkg/internal/source/internal_test.go
  pkg/internal/source/kind.go
  pkg/source/source.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3102 :bug: Fix custom path for webhooks conflict
  pkg/builder/webhook.go
  pkg/builder/webhook_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#3168 :seedling: Remove redundant WithLowPriorityWhenUnchanged in builder
  pkg/builder/controller.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3169 🌱 Fix godoc of TypedEventHandler
  pkg/handler/eventhandler.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3170 🌱 Mention the SkipNameValidation option in the name validation error
  pkg/controller/name.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3165 ✨ Adopt native histograms
  pkg/internal/controller/metrics/metrics.go
  pkg/internal/metrics/workqueue.go
  pkg/webhook/internal/metrics/metrics.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#2278 ✨ envtest: Add Environment.KubeConfig field
  pkg/envtest/envtest_test.go
  pkg/envtest/server.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#3174 :seedling: TypedEnqueueRequestForOwner: Decrease priority when unchanged
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3166 ✨Add RELEASE_TAG to tools/setup-envtest to show binary version with setup-envtest version
  .github/workflows/release.yaml
  Makefile
  tools/setup-envtest/main.go
  tools/setup-envtest/version/version.go
  tools/setup-envtest/version/version_suite_test.go
  tools/setup-envtest/version/version_test.go
  tools/setup-envtest/workflows/workflows.go
  tools/setup-envtest/workflows/workflows_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3176 🌱 Adopt WarningHandlerWithContext
  pkg/client/client.go
  pkg/client/example_test.go
  pkg/log/warning_handler.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#3177 🐛 Fix Godoc for version.Version in setupenvtest
  tools/setup-envtest/version/version.go
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3179 [release-0.20] :seedling: Handlers: Default to LowPriorityWhenUnchanged without a wrapper
  pkg/builder/controller.go
  pkg/handler/enqueue.go
  pkg/handler/enqueue_mapped.go
  pkg/handler/enqueue_owner.go
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#3181 📖Golang 1.24+ in setup-envtest/README.md
  tools/setup-envtest/README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm, tide/merge-method-squash, ok-to-test

#3185 :seedling: Clarify that controller-runtime is not a kubebuilder subproject
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm
