Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-05, with the labels that each got.

#3204 🌱Move to v0.33 k8s deps
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#3186 :sparkles: Allow panic as log level
  pkg/log/zap/flags.go
  pkg/log/zap/zap.go
  pkg/log/zap/zap_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test

#3215 🌱 Bump setup-envtest to k8s.io/apimachinery v0.33.0
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, approved, size/S, lgtm

#3195 ⚠ fix: Stop accumulating lists in multi-namespace cache implementation
  pkg/cache/cache_test.go
  pkg/cache/multi_namespace_cache.go
Labels: cncf-cla: yes, approved, size/S, lgtm, tide/merge-method-squash, ok-to-test

#3193 📖 Document pitfalls of CreateOrUpdate and CreateOrPatch
  pkg/controller/controllerutil/controllerutil.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#3208 🐛Use k8s.io/apimachinery/pkg/util/json to unmarshal in fakeclient
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#3187 🌱ci: Update golangci-lint to v2.1.6 and adjust configuration
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  examples/builtins/controller.go
  examples/crd/main.go
  examples/crd/pkg/groupversion_info.go
  pkg/cache/cache_test.go
  pkg/cache/internal/informers.go
  pkg/client/config/config_test.go
  pkg/client/fake/client.go
  pkg/envtest/webhook.go
Labels: cncf-cla: yes, size/L, approved, lgtm, ok-to-test

#3225 📖 Update README with compatability matrix
  README.md
Labels: cncf-cla: yes, approved, size/XS, lgtm

#3228 :warning: Fakeclient: Remove support for objects with pointer meta
  pkg/client/fake/client_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm
