Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-06, with the labels that each got.

#3236 :seedling: Bump k8s.io/* deps to v0.34.0-alpha.1
  .gomodcheck.yaml
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#3237 ✨ feat: add support for custom labels on leader election leases ✨
  pkg/leaderelection/leader_election.go
  pkg/manager/manager.go
  pkg/manager/manager_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, ok-to-test

#2981 ✨ Fakeclient: Add apply support
  go.mod
  pkg/client/fake/client.go
  pkg/client/fake/client_test.go
  pkg/client/fake/typeconverter.go
  pkg/client/fake/typeconverter_test.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#3250 :bug: Priorityqueue: Shutdown on shutdown
  pkg/controller/priorityqueue/priorityqueue.go
Labels: cncf-cla: yes, approved, size/S, lgtm
