Repository kubernetes-sigs/controller-runtime, pull requests merged in 2025-08, with the labels that each got.

#3270 :seedling: Bump k8s.io/* deps to v0.34.0-rc.1
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  go.sum
  tools/setup-envtest/go.mod
  tools/setup-envtest/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#3273 :seedling: Certwatcher: Don't require leaderelection
  pkg/certwatcher/certwatcher.go
  pkg/certwatcher/certwatcher_test.go
Labels: cncf-cla: yes, approved, size/S, lgtm

#3278 ✨ Handle panics during conversion more gracefully
  pkg/webhook/conversion/conversion.go
  pkg/webhook/conversion/conversion_test.go
  pkg/webhook/conversion/metrics/metrics.go
  pkg/webhook/conversion/testdata/api/v1/externaljob_types.go
  pkg/webhook/conversion/testdata/api/v1/zz_generated.deepcopy.go
  pkg/webhook/conversion/testdata/api/v2/externaljob_types.go
  pkg/webhook/conversion/testdata/api/v2/zz_generated.deepcopy.go
  pkg/webhook/conversion/testdata/api/v3/externaljob_types.go
  pkg/webhook/conversion/testdata/api/v3/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3279 ⚠️ Default selectors to Nothing if it is nil for `MatchingLabelsSelector` and `MatchingFieldsSelector`
  pkg/client/options.go
  pkg/client/options_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm, tide/merge-method-squash, ok-to-test

#3277 :book: Docs for SyncPeriod: No sync from api-server.
  pkg/cache/cache.go
Labels: cncf-cla: yes, approved, size/S, needs-ok-to-test, lgtm

#3290 :sparkles: WithLowPriorityWhenUnchanged: Set Priority for all add methods
  pkg/handler/eventhandler.go
  pkg/handler/eventhandler_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#3280 ✨ envtest: search the assets index for latest of a release series
  examples/scratch-env/go.mod
  examples/scratch-env/go.sum
  go.mod
  pkg/envtest/binaries.go
  pkg/envtest/binaries_test.go
Labels: cncf-cla: yes, size/L, approved, lgtm, tide/merge-method-squash, ok-to-test

#3293 🌱 certwatcher: add instance-specific logger with cert/key context
  pkg/certwatcher/certwatcher.go
Labels: cncf-cla: yes, approved, size/S, lgtm, ok-to-test
